files:
  - source: /source/casaos-ui/en.json
    translation: /translate/casaos-ui/%locale_with_underscore%.%file_extension%
  - source: /source/appstore/en.json
    translation: /translate/appstore/%locale_with_underscore%.%file_extension%
