// English

export default {
    // Commons
    "": "",
    "OK": "OK",
    "Cancel": "Annuller",
    "Submit": "Indsend",
    "Back": "Tilbage",
    "Edit": "Rediger",
    "Update": "Opdater",
    "Create": "Opret",
    "Next": "Næste",
    "Close": "Luk",
    "Select": "Vælg",
    "Save": "Gem",
    "Add": "Tilføj",
    "Go": "Gå",
    "Import": "Import",
    "Low": "Lav",
    "Medium": "Medium",
    "High": "Høj",
    "Language": "Sprog",
    "Change": "Skift",
    "Start": "Start",

    "This field is required": "Dette felt er påkrævet",
    "This field must be a valid email": "Dette felt skal være en gyldig e-mail",
    "This field confirmation does not match": "Bekræftelsefeltet stemmer ikke overens",
    "This field must have 2 options": "Dette felt skal have 2 muligheder",
    "This field must have more than 5 characters": "Dette felt skal have mere end 5 tegn",
    "You entered an invalid RFC1123 hostname": "Du har indtastet et ugyldigt RFC1123 værtsnavn",

    // Init Page
    "Welcome to CasaOS": "Velkommen til CasaOS",
    "Let's create your initial account": "Lad os oprette din første konto",
    "Go →": "Gå →",
    "Create Account": "Opret konto",
    "Username": "Brugernavn",
    "Confirm Password": "Bekræft kodeord",
    "Username or Password error!": "Brugernavn eller koderod fejl!",
    "All things done!": "Alle ting udført!",


    // Login
    "Login": "Login",
    "Password error!": "Kodeord fejl!",

    // Account
    "Account": "Konto",
    "Logout": "Logud",
    "Name": "Navn",
    "Password": "Kodeord",
    "Change name": "Skift navn",
    "Change Password": "Skift kodeord",
    "Original password": "Oprindelige kodeord",
    "New password": "Nyt kodeord",
    "Confirm the new password again": "Bekræft det nye kodeord igen",

    // Dashboard Settings
    "Settings": "Indstillinger",
    "Dashboard Setting": "Indstillinger for dashboard",
    "Search Engine": "Søgemaskine",
    "WebUI Port": "WebUI Port",
    "Currently the latest version": "I øjeblikket den seneste version",
    "A new version is available!": "En ny version er tilgængeligt!",
    "Edit Web UI port": "Rediger WebUI port",
    "Automount USB Drive": "Automonter USB-drev",
    "Wallpaper": "Baggrundsbillede",
    "Change wallpaper": "Skift baggrundsbillede",
    "Show Search Bar": "Vis søgelinje",
    "Show Recommended Apps": "Vis anbefalede apps",
    "Upgrade Now": "Opgrader nu",
    "Enabling this function may cause boot failures when the Raspberry Pi device is booted from USB": "Aktivering af denne funktion kan forårsage opstartsfejl, når Raspberry Pi enheden startes fra USB",

    // Terminal & Logs
    "Terminal & Logs": "Terminal & Logs",
    "Terminal": "Terminal",
    "Logs": "Logs",

    // Widgets
    "Widgets Settings": "Indstillinger for widgets",
    "Time": "Tid",
    "Cores": "Kerner",
    "System Status": "System Status",
    "Storage Status": "Opbevaringsstatus",
    "Network Status": "Netværk Status",
    "available of": "{avl} tilgængelig af {total}",

    // Search 
    "Search...": "Søg...",

    // Sync
    "Sync your data": "Synkroniser dine data",
    "Use Syncthing to sync your files between multiple devices.": "Brug Syncthing til at synkronisere dine filer mellem flere enheder.",
    "Install": "Installer",
    "Config": "Konfig",
    "Total": "Total",
    "Failed to start, please try again.": "Kunne ikke starte. Prøv venligst igen.",
    "Syncthing is not running, start it?": "Syncthing kører ikke, start det?",
    "Starting Syncthing...": "Starter Syncthing...",

    // Iot
    "Have an idea? Shoot it on Discord!": "Har du en ide? Fortæl os om den på Discord!",
    "Smarten up your home": "Gør dit hjem smartere",
    "We want to give you a smart home experience with privacy, high speed, and localized storage.": "Vi ønsker at give dig en smart home-oplevelse med privatliv, høj hastighed og lokaliseret opbevaring.",
    "In development": "Under udvikling",

    // Apps
    "Apps": "Apps",
    "App": "App",
    "Open": "Åben",
    "Setting": "Indstilling",
    "Uninstall": "Afinstaller",
    "Attention": "Opmærksomhed",
    "Data cannot be recovered after deletion! <br>Continue on to uninstall this application?": "Data kan ikke gendannes efter sletning! <br>Vil du fortsætte med at afinstallere denne applikation?",
    "Featured Apps": "Udvalgte apps",
    "Custom Install": "Brugerdefineret installation",
    "Continue in background": "Fortsæt i baggrunden",
    "Install a new App manually": "Installer en ny app manuelt",
    "Docker Image": "Docker Image",
    "App name": "App navn",
    "Icon URL": "Ikon URL",
    "Network": "Netværk",
    "Privileged": "Privilegeret",
    "Container Command": "Containerkommando",
    "Container Capabilities (cap-add)": "Container kapaciteter (cap-add)",
    "Container Hostname": "Container værtsnavn",
    "Hostname of app container": "Værtsnavn for app container",
    "Ports": "Porte",
    "Volumes": "Volumener",
    "Environment Variables": "Miljøvariabler",
    "Devices": "Enheder",
    "Memory Limit": "Hukommelse begræsning",
    "CPU Shares": "CPU andele",
    "Restart Policy": "Genstartspolitik",
    "App Description": "App beskrivelse",
    "No ports now, click “+” to add one.": "Ingen porte nu, klik på "+" for at tilføje en.",
    "No volumes now, click “+” to add one.": "Ingen volumener nu, klik på "+" for at tilføje en.",
    "No environment variables now, click “+” to add one.": "Ingen miljøvariabler nu, klik på "+" for at tilføje en.",
    "No devices now, click “+” to add one.": "Ingen enheder nu, klik på "+" for at tilføje en.",
    "No commands now, click “+” to add one.": "Ingen kommandoer nu, klik på "+" for at tilføje en.",
    "e.g.,hello-world:latest": "f.eks. Hello-world:seneste",
    "Your custom App Name": "Dit brugerdefinerede appnavn",
    "Your custom icon URL": "Din tilpassede ikon-URL",
    "Installing": "Installere",
    "Export AppFile": "Eksporter AppFile",
    "AppFile": "AppFile",
    "Drop your app file here or click to upload": "Slip din app fil her, eller klik for at uploade",
    "Host": "Host",
    "Container": "Container",
    "Key": "Nøgle",
    "Value": "Værdi",
    "Protocol": "Protokol",
    "This is not a valid json file.": "Dette er ikke en gyldig json-fil.",
    "Your browser does not support file reading.": "Din browser understøtter ikke fillæsning.",
    "has been selected": "er blevet valgt",
    "Please fill correct command line": "Udfyld venligst den korrekte kommandolinje",
    "Please import a valid App file": "Importer venligst en gyldig app-fil",
    "AutoFill only helps you to complete most of the configuration.": "AutoFyld hjælper dig kun med at fuldføre det meste af konfigurationen.",
    "Some configuration information such as:": "Nogle konfigurationsoplysninger såsom:",
    "the port and path of the Web UI": "porten og stien til webbrugergrænsefladen",
    "the mount location of the volume or file": "monteringsstedet for diskenheden eller filen",
    "the port mapping of the Host": "portkortlægningen af ​​værten",
    "optional configuration items": "valgfrie konfigurationselementer",
    "These include but are not limited to these cases and <b>still need to be confirmed or modified by you.</b>": "Disse omfatter, men er ikke begrænset til, disse tilfælde og <b>skal stadig bekræftes eller ændres af dig.</b>",
    "Feel free to suggest improvements to this feature in Discord Server!": "Du er velkommen til at foreslå forbedringer af denne funktion i Discord Server!",
    "Using localhost or 127.0.0.1 will cause the application to be inaccessible, please use the real ip to access.": "Brug af localhost eller 127.0.0.1 vil medføre, at applikationen bliver utilgængelig. Brug venligst den rigtige ip for at få adgang.",
    "CATEGORY": "KATEGORI",
    "DEVELOPER": "UDVIKLER",
    "REQUIRE": "KRÆVE",
    "MEMORY": "HUKOMMELSE",
    "DISK": "DISK",
    "App Store": "App Store",
    "Community Apps": "Fællesskabsapps",
    "From community contributors, not optimized for CasaOS, but provides a basic App experience.": "Fra fællesskabsbidragydere, ikke optimeret til CasaOS, men giver en grundlæggende appoplevelse.",
    "Sort by": "Sorter efter",
    "Click icon to import.": "Klik på ikonet for at importere.",
    "Drag icons to sort.": "Træk ikoner for at sortere.",
    "Import to CasaOS": "Importer til CasaOS",
    "Existing Docker Apps": "Eksisterende Docker-apps",
    "Port [Please add a ports set first]": "Port [Tilføj venligst et portsæt først]",
    "[Optional]": "[Valgfri]",
    "Notice: If there are multiple services, only the first set can be analyzed correctly": "Bemærk: Hvis der er flere tjenester, kan kun det første sæt analyseres korrekt",
    "There was an error loading the data, please try again!": "Der opstod en fejl under indlæsning af data, prøv venligst igen!",

    //Storage
    "Create Storage": "Opret lagerplads",
    "Storage Manager": "Lagermanager",
    "Storage": "Lager",
    "Drive": "Drive",
    "Single Drive Storage": "Opbevaring på enkelt drev",
    "Format": "Formater",
    "Remove": "Fjern",
    "Available Total": "{navn} | Tilgængelig: {avl} (Total: {total})",
    "Health": "Sundhed",
    "Healthy": "Sund og rask",
    "Damage": "Skade",
    "Temp": "Temperatur",
    "WARNING!": "ADVARSEL!",
    "This selected drive will be emptied if there is data on it. Make sure again that there is no important data on the selected drive that has not been backed up. If there is data to be migrated, the related apps will be stopped during the migration process.": "Dette valgte drev vil blive tømt, hvis der er data på det. Sørg igen for, at der ikke er vigtige data på det valgte drev, som ikke er blevet sikkerhedskopieret. Hvis der er data, der skal migreres, vil de relaterede apps blive stoppet under migreringsprocessen.",
    "Creation in progress": "Oprettelse i gang",
    "Apply": "Anvend",
    "Just Mount": "Bare monter",
    "Storage Name": "Lagernavn",
    "Choose Drive": "Vælg Drev",
    "Enter the password to continue:": "Skriv kodeordet for at fortsætte:",
    "Used": "Brugt",
    "CasaOS reserves 1% of file space when creating storage in EXT4 format.": "CasaOS reserverer 1% af filpladsen, når der oprettes lager i EXT4-format.",
    "The selected drive will be emptied.": "Det valgte drev tømmes.",
    "Please make sure again that there is no important data on the selected drive that needs to be backed up.": "Sørg for igen, at der ikke er vigtige data på det valgte drev, der skal sikkerhedskopieres.",
    "The drive you select can be used directly as storage.": "Det drev, du vælger, kan bruges direkte som lager.",
    "You can also choose to create it after formatting. If formatted, the selected drive will be emptied.": "Du kan også vælge at oprette den efter formatering. Hvis det formateres, vil det valgte drev blive tømt.",
    "Format and Create": "Formater og opret",

    // Feedback
    "Join Discord": "Tilmeld dig Discord",
    "Visit our Github": "Besøg vores Github",
    "Bug report": "Fejlrapport",
    "Title": "Titel",
    "Describe the bug": "Beskriv fejlen",
    "A clear and concise description of what the bug is.": "En klar og kortfattet beskrivelse af, hvad fejlen er.",
    "System infomation": "Systeminformation",

    // Files
    "Files": "Files",
    "Upload or Create": "Upload or Create",
    "Upload Files": "Upload Files",
    "Upload Folder": "Upload Folder",
    "New Folder": "New Folder",
    "New File": "New File",
    "Change View": "Change View",
    "Upload to": "Upload to",
    "Uploading": "Uploading",
    "Completed": "Completed",
    "success": "Success",
    "error": "Error",
    "uploading": "Uploading",
    "paused": "Paused",
    "waiting": "Waiting",
    "Download": "Download",
    "Copy Path": "Copy Path",
    "Rename": "Rename",
    "Cut": "Cut",
    "Copy": "Copy",
    "Delete": "Delete",
    "Are you sure?": "Are you sure?",
    "Paste": "Paste",
    "Refresh": "Refresh",
    "Code Editor": "Code Editor",
    "Saved": "Saved",
    "Want to save?": "Want to save?",
    "Your changes will be lost if you don’t save them.": "Your changes will be lost if you don't save them.",
    "Don’t Save": "Don't Save",
    "Drop your files here to upload": "Drop your files here to upload",
    "or": "or",
    "Date Modified": "Date Modified",
    "Size": "Size",
    "Play in IINA": "Play in IINA",
    "Play in PotPlayer": "Play in PotPlayer",
    "Play in VLC": "Play in VLC",
    "Download in preparation...": "Download in preparation...",
    "Copied to clipboard": "Copied to clipboard",
    "Previous": "Previous",
    "Zoom in": "Zoom in",
    "Rotate": "Rotate",
    "Reset": "Reset",
    "Zoom out": "Zoom out",
    "INext": "Next",
    "Move": "Move",
    "Current Tasks": "Current Tasks",
    "Deleting files": "Deleting files",
    "Are you sure you want to <b>delete</b> these files? This action cannot be undone.": "Are you sure you want to <b>delete</b> these files? This action cannot be undone.",
    "select-items": "Select {num} items",
    "total-items": "Total {num} items",
    "cancel-all": "Cancel All",
    "Paste - Overwrite": "Paste - Overwrite",
    "Paste - Skip": "Paste - Skip",
    "Set as wallpaper": "Set as wallpaper",
    "Set wallpaper successfully.": "Set wallpaper successfully.",
    "Save failed, please try again!": "Save failed, please try again!",
    "Upload failed, please try again!": "Upload failed, please try again!",

}
