// Hungarian

export default {
    // Commons
    "": "",
    "OK": "OK",
    "Cancel": "Mégsem",
    "Submit": "Beküldés",
    "Back": "Vissza",
    "Edit": "Szerkesztés",
    "Update": "Frissítés",
    "Create": "Létrehozás",
    "Next": "Következő",
    "Close": "Bezárás",
    "Select": "Kiválasztás",
    "Save": "Mentés",
    "Add": "Hozzáadás",
    "Go": "Mehet",
    "Import": "Importálás",
    "Low": "Alacsony",
    "Medium": "Közepes",
    "High": "Magas",
    "Language": "Nyelv",

    "This field is required": "A mező kitöltése kötelező",
    "This field must be a valid email": "A mezőnek érvényes e-mail címet kell tartalmaznia",
    "This field confirmation does not match": "A megerősítés mező nem egyezik",
    "This field must have 2 options": "A mezőnek 2 lehetőséget kell tartalmaznia",
    "This field must have more than 5 characters": "A mezőnek legalább 5 karaktert kell tartalmaznia",
    "You entered an invalid RFC1123 hostname": "A megadott RFC1123 hosztnév érvénytelen",

    // Init Page
    "Welcome to CasaOS": "Üdvözöl a CasaOS",
    "Let's create your initial account": "Hozd létre fiókod",
    "Go →": "Gyerünk →",
    "Create Account": "Fiók létrehozása",
    "Username": "Felhasználónév",
    "Confirm Password": "Jelszó megerősítése",
    "Username or Password error!": "Felhasználónév vagy jelszó hiba!",
    "All things done!": "Minden elkészült!",


    // Login
    "Login": "Bejelentkezés",
    "Password error!": "Jelszó hiba!",

    // Account
    "Account": "Fiók",
    "Logout": "Kijelentkezés",
    "Name": "Név",
    "Password": "Jelszó",
    "Change name": "Név módosítása",
    "Change Password": "Jelszó módosítása",
    "Original password": "Régi jelszó",
    "New password": "Új jelszó",
    "Confirm the new password again": "Új jelszó megerősítése",

    // Dashboard Settings
    "Settings": "Beállítások",
    "Dashboard Setting": "Irányítópult beállítása",
    "Search Engine": "Keresőmotor",
    "WebUI Port": "WebUI port",
    "Currently the latest version": "Legújabb verzió",
    "A new version is available!": "Új verzió áll rendelkezésre!",
    "Edit Web UI port": "WebUI port módosítása",
    "Automount USB Drive": "USB meghajtó automatikus csatolása",
    "Upgrade Now": "Frissítés most",
    "Enabling this function may cause boot failures when the Raspberry Pi device is booted from USB": "A funkció engedélyezésével előfordulhatnak indítási hibák abban az esetben, ha a Raspberry Pi USB-ről indul.",

    // Terminal & Logs
    "Terminal & Logs": "Parancssor és naplók",
    "Terminal": "Parancssor",
    "Logs": "Naplók",

    // Widgets
    "Widgets Settings": "Widgetek beállításai",
    "Time": "Idő",
    "Cores": "Cores",
    "System Status": "Rendszer állapota",
    "Storage Status": "Lemez állapota",
    "Network Status": "Hálózat állapota",
    "available of": "{avl} elérhető / {total} összesen",

    // Search 
    "Search...": "Keresés...",

    // Sync
    "Sync your data": "Adatok szinkronizálása",
    "Follow the guide to start syncing your files across multiple devices.": "Kövesd az útmutatót a fájlok több eszközön történő szinkronizálásához.",
    "Go !": "Mehet !",
    "Sync Guide": "Szinkronizálási útmutató",
    "Install": "Telepítés",
    "Config": "Beállítás",
    "Complete": "Befejezés",
    "Download Syncthing on the device you want to sync with CasaOS": "Töltsd le a Syncthing alkalmazást arra az eszközre, amelyet szinkronizálni szeretnél a CasaOS rendszerrel.",
    "Get Syncthing for": "Syncthing alkalmazás beszerzése erre: {os}",
    "Download APK": "APK letöltése",
    "Show all Platforms": "Összes platform megjelenítése",
    'Install and open the downloaded application, then click the "Next" button.': 'Telepítsd és nyisd meg a letöltött alkalmazást, majd kattints a "Tovább" gombra.',
    "Device ID": "Eszközazonosító",
    "Fill in your Device ID to continue": "A folytatáshoz add meg az eszközazonosítót",
    "How to get Device ID": "Hogy szerezhetem meg az eszközazonosítót?",
    "What do I need to do on my device?": "Mi a teendő az eszközömön?",
    "Open the SyncTrayzor": "Nyisd meg a SyncTrayzor alkalmazást",
    "Find the Device ID": "Keresd meg az eszközazonosítót",
    "Add new device on your device": "Add hozzá az eszközt",
    "Add new folder on your device": "Add hozzá a mappát",
    "Done!": "Kész!",

    "Open Syncthing in the Launchpad": "Nyisd meg a Syncthing alkalmazást az indítópulton",
    "Find the Syncthing icon in the menubar": "Keresd meg a Syncthing alkalmazás ikonját a menüsorban",
    "Open Syncthing": "Nyisd meg a Syncthing alkalmazást",
    "Open the menu": "Nyisd meg a menüt",
    'Choose "Show device ID"': 'Válaszd az "Eszközazonosító megjelenítése" opciót',
    "Copy the Device ID": "Másold ki az eszközazonosítót",
    "There you go!": "Már kész is vagy!",
    "Your data has started to sync.It may take some minutes to fulfill synchronization.": "Az adatok szinkronizálása megkezdődött.<br>Ez eltarthat néhány percig.",
    "Up to Date": "Naprakész",
    "Synchronizing": "Szinkronizálás alatt",
    "Synchronized": "Szinkronizált",
    "Total": "Összesen",
    "Add New Device": "Új eszköz hozzáadása",

    // Iot
    "Have an idea? Shoot it on Discord!": "Van egy jó ötleted? Oszd meg velünk Discordon!",
    "Smarten up your home": "Okosítsd fel otthonod",
    "We want to give you a smart home experience with privacy, high speed, and localized storage.": "Szeretnénk professzionális otthoni élményt biztosítani adatvédelmi, nagy sebességű és helyhez kötött tárolási lehetőségekkel.",
    "In development": "Fejlesztés alatt",

    // Apps
    "Apps": "Alkalmazások",
    "App": "Alkalmazás",
    "Open": "Megnyitás",
    "Setting": "Beállítás",
    "Uninstall": "Eltávolítás",
    "Attention": "Figyelmeztetés",
    "Data cannot be recovered after deletion! <br>Continue on to uninstall this application?": "Törlés után az adatok nem állíthatók helyre! <br>Folytatod az alkalmazás eltávolítását?",
    "Featured Apps": "Kiemelt alkalmazások",
    "Custom Install": "Egyéni telepítés",
    "Continue in background": "Folytatás a háttérben",
    "Install a new App manually": "Új alkalmazás manuális telepítése",
    "Docker Image": "Docker képfájl",
    "App name": "Alkalmazás neve",
    "Icon URL": "Ikon URL",
    "Network": "Hálózat",
    "Privileged": "Privilegizált",
    "Container Command": "Konténer parancs",
    "Container Capabilities (cap-add)": "Konténer képességek (cap-add)",
    "Container Hostname": "Konténer hostnév",
    "Hostname of app container": "Alkalmazás konténerének hostneve",
    "Ports": "Portok",
    "Volumes": "Kötetek",
    "Environment Variables": "Környezeti változók",
    "Devices": "Eszközök",
    "Memory Limit": "Memória limit",
    "CPU Shares": "CPU erőforrás elosztás",
    "Restart Policy": "Újraindítási eljárásmód",
    "App Description": "Alkalmazás leírása",
    "No ports now, click “+” to add one.": "Még nincsenek hozzáadott portok, kattints a “+” gombra a hozzáadáshoz.",
    "No volumes now, click “+” to add one.": "Még nincsenek hozzáadott kötetek, kattints a “+” gombra a hozzáadáshoz.",
    "No environment variables now, click “+” to add one.": "Még nincsenek hozzáadott környezeti változók, kattints a “+” gombra a hozzáadáshoz.",
    "No devices now, click “+” to add one.": "Még nincsenek hozzáadott eszközök, kattints a “+” gombra a hozzáadáshoz.",
    "No commands now, click “+” to add one.": "Még nincsenek hozzáadott parancsok, kattints a “+” gombra a hozzáadáshoz.",
    "e.g.,hello-world:latest": "pl.,hello-world:latest",
    "Your custom App Name": "Egyéni alkalmazás név",
    "Your custom icon URL": "Egyéni ikon URL",
    "Installing": "Telepítés",
    "Export AppFile": "Alkalmazásfájl exportálása",
    "AppFile": "Alkalmazásfájl",
    "Drop your app file here or click to upload": "Húzd ide az alkalmazásfájlt, vagy kattints a feltöltésre",
    "Host": "Hoszt",
    "Container": "Konténer",
    "Key": "Kulcs",
    "Value": "Érték",
    "Protocol": "Protokol",
    "This is not a valid json file.": "Ez egy érvénytelen json fájl.",
    "Your browser does not support file reading.": "A böngészője nem támogatja a fájlolvasást.",
    "has been selected": "kiválasztva",
    "Please fill correct command line": "Helyes parancssor megadása szükséges",
    "Please import a valid App file": "Érvényes alkalmazásfájl megadása szükséges",
    "AutoFill only helps you to complete most of the configuration.": "Az AutoFill csak a konfiguráció nagy részének kitöltésében segít.",
    "Some configuration information such as:": "Néhány konfigurációs információ, mint például:",
    "the port and path of the Web UI": "a Web UI portja és elérési útvonala",
    "the mount location of the volume or file": "a kötet vagy fájl csatolási helye",
    "the port mapping of the Host": "a Hoszt port-kiosztása",
    "optional configuration items": "opcionális konfigurációs elemek",
    "These include but are not limited to these cases and <b>still need to be confirmed or modified by you.</b>": "Ezek egyes esetekben korlátozottan érhetők el, ezért <b>Neked kell jóváhagyni vagy módosítani ezeket a beállításokat.</b>",
    "Feel free to suggest improvements to this feature in Discord Server!": "Nyugodtan javasolj fejlesztéseket a Discord szerveren!",
    "Using localhost or 127.0.0.1 will cause the application to be inaccessible, please use the real ip to access.": "A localhost vagy 127.0.0.1 ip cím használata esetén az alkalmazás elérhetetlenné válik, használj valós ip címet a hozzáféréshez.",
    "CATEGORY": "KATEGÓRIA",
    "DEVELOPER": "FEJLESZTŐ",
    "REQUIRE": "SZÜKSÉGES",
    "MEMORY": "MEMÓRIA",
    "DISK": "TÁRHELY",
    "App Store": "Áruház",
    "Community Apps": "Közösségi alkalmazások",
    "From community contributors, not optimized for CasaOS, but provides a basic App experience.": "A közösség közreműködőitől, nem optimalizálták a CasaOS-re, de az alapvető Alkalmazás-élményt biztosítja.",
    "Sort by": "Rendezés",
    "Click icon to import apps into CasaOS": "Kattints ide az alkalmazások importálásához",
    "Drag icons to sort": "Húzd az ikonokat a rendezéshez",
    "Import to CasaOS": "Importálás",
    "Existing Docker Apps": "Létező Docker alkalmazások",
    "Port [Please add a ports set first]": "Port [Először adj meg portokat]",
    "[Optional]": "[Opcionális]",
    "Notice: If there are multiple services, only the first set can be analyzed correctly": "Megjegyzés: Több szolgáltatás megadása esetén csak az első feldolgozása lehetséges.",
    "No need": "Nem szükséges",


    //Storage
    "Create Storage": "Tároló létrehozása",
    "Storage Manager": "Tárhelykezelő",
    "Storage": "Tárhely",
    "Drive": "Meghajtó",
    "Single Drive Storage": "Single Drive tároló",
    "Format": "Formátum",
    "Remove": "Eltávolítás",
    "Available Total": "{name} | Elérhető: {avl} (Összes: {total})",
    "Health": "Állapot",
    "Healthy": "Kiváló",
    "Damage": "Sérült",
    "Temp": "Hőmérséklet",
    "WARNING!": "FIGYELMEZTETÉS!",
    "This selected drive will be emptied if there is data on it. Make sure again that there is no important data on the selected drive that has not been backed up. If there is data to be migrated, the related apps will be stopped during the migration process.": "A kiválasztott meghajtó tartalma eltávolításra kerül. Ismét győződj meg arról, hogy a kiválasztott meghajtón nincsenek olyan fontos adatok, amelyekről nem készült biztonsági mentés. Amennyiben vannak mentésre váró adatok, a kapcsolódó alkalmazások leállnak a mentési folyamat alatt.",
    "Creation in progress": "Létrehozás folyamatban",
    "Apply": "Alkalmazás",
    "Just Mount": "Csak csatlakoztatás",
    "Storage Name": "Tárhely neve",
    "Choose Drive": "Meghajtó kiválasztása",
    "Enter the password to continue:": "A folytatáshoz add meg a jelszót:",
    "Used": "Felhasznált",
    "CasaOS reserves 1% of file space when creating storage in EXT4 format.": "A CasaOS az EXT4 formátumú tárolók létrehozásakor a fájlterület 1%-át fenntartja.",
    "The selected drive will be emptied.": "A kiválasztott meghajtó tartalma eltávolításra kerül.",
    "Please make sure again that there is no important data on the selected drive that needs to be backed up.": "Ismét győződj meg arról, hogy a kiválasztott meghajtón nincsenek olyan fontos adatok, amelyekről biztonsági mentést szükséges készíteni.",
    "The drive you select can be used directly as storage.": "A kiválasztott meghajtó közvetlenül tárhelyként használható.",
    "You can also choose to create it after formatting. If formatted, the selected drive will be emptied.": "Az is lehetséges, hogy a létrehozás a formázás után történjen meg. Formázás esetén a kiválasztott meghajtó tartalma eltávolításra kerül.",
    "Format and Create": "Formázás és létrehozás",

    // Feedback
    "Join Discord": "Discord csatlakozás",
    "Visit our Github": "Megtekintés Github-on",
    "Bug report": "Hiba jelentése",
    "Title": "Cím",
    "Describe the bug": "Hiba leírása",
    "A clear and concise description of what the bug is.": "A hiba egyértelmű és tömör leírása.",
    "System infomation": "Rendszerinformáció",

    // Files
    "Files": "Fájlok",
    "Upload or Create": "Feltöltés vagy létrehozás",
    "Upload Files": "Fájlok feltöltése",
    "Upload Folder": "Mappa feltöltése",
    "New Folder": "Új mappa",
    "New File": "Új fájl",
    "Change View": "Nézet megváltoztatása",
    "Upload to": "Feltöltés ide: ",
    "Uploading": "Feltöltés",
    "Completed": "Befejezve",
    "success": "Sikeres",
    "error": "Hiba",
    "uploading": "Feltöltés",
    "paused": "Megállítva",
    "waiting": "Várakozás",
    "Download": "Letöltés",
    "Copy Path": "Útvonal másolása",
    "Rename": "Átnevezés",
    "Cut": "Kivágás",
    "Copy": "Másolás",
    "Delete": "Törlés",
    "Are you sure?": "Biztos vagy benne?",
    "Paste": "Beillesztés",
    "Refresh": "Frissítés",
    "Code Editor": "Kódszerkesztő",
    "Saved": "Mentve",
    "Want to save?": "Menteni szeretnéd?",
    "Your changes will be lost if you don’t save them.": "A módosítások elvesznek, ha nem mented el őket.",
    "Don’t Save": "Nincs mentés",
    "Drop your files here to upload": "Húzd ide a fájlokat a feltöltéshez",
    "or": "vagy",
    "Date Modified": "Módosítás ideje",
    "Size": "Méret",
    "Play in IINA": "Lejátszás ezzel: IINA",
    "Play in PotPlayer": "Lejátszás ezzel: PotPlayer",
    "Play in VLC": "Lejátszás ezzel: VLC",
    "Download in preparation...": "Letöltés előkészületben...",
    "Copied to clipboard": "Vágólapra másolva",
    "Previous": "Előző",
    "Zoom in": "Közelítés",
    "Rotate": "Forgatás",
    "Reset": "Visszaállítás",
    "Zoom out": "Távolítás",
    "INext": "Következő",

    /* ******************************
    * Share Section
    ********************************/
    "Share module name": "CasaConnect",
    // Main
    "More info": "További információk",
    "Edit Info": "Információk módosítása",
    "Copy My Share ID": "Megosztási azonosító másolása",
    "Add Friend": "Barát hozzáadása",
    "Friends": "Barátok",
    "Downloads": "Letöltések",
    "Notification": "Értesítések",
    "Upload not supported!": "A feltöltés nem támogatott!",
    "Select a friend to view his share.": "Válassz ki egy barátot a megosztás megtekintéséhez.", //
    "There are no files in the current folder.": "A jelenlegi mappa nem tartalmaz fájlokat.",
    "has been copied to the clipboard": "vágólapra másolva",
    "is offline": "nem érhető el",
    "Home": "Home",
    "Forward": "Továbbítás",
    // User Context
    "Edit remark": "Megjegyzés módosítása",
    "Unblock this friend": "Barát tiltásának feloldása",
    "Block this friend": "Barát tiltása",
    "Delete friend": "Barát törlése",
    "Blocked this friend": "Barát letiltva",
    "Unblocked this friend": "Barát tiltása feloldva",
    "Blocked failed": "Sikertelen tiltás",
    "Deleted this friend": "Barát törölve",
    "Delete failed": "Sikertelen törlés",
    "Copy friend's ID": "Barát azonosítójának másolása",

    // Tour
    "Skip": "Következő",
    "Prev": "Vissza",
    "Let's Go": "Mehet!",
    "Here is your avatar, where you can change your personal information and get your ID to share with your friends.": "Itt találod az avatarodat, melyre kattintva megváltoztathatod személyes adataidat és elérheted a megosztási azonosítódat.",
    "Click \"+\" and enter your friend's ID to send a friend request.": "Kattints a \"+\" gombra, majd add meg a barátod azonosítóját a barátkérelem elküldéséhez.",
    "Browse your download progress and download history here.": "Letöltési folyamatok és a letöltési előzmények megtekintése",
    "Modify your shared folders, and default download path here.": "Megosztott mappák és az alapértelmezett letöltési útvonal módosítása",
    "Well, let's start using it!": "Nos, már használhatod is!",

    // Download List
    "Downloading": "Letöltés",
    "D-Completed": "Befejezve",
    "D-Total": "Teljes",
    "D-Name": "Név",
    "D-Size": "Méret",
    "D-Progress": "Állapot",
    "D-Retry": "Újra",
    "Cancel Download": "Letöltés visszavonása",
    "Delete this record": "Felvétel törlése",
    "Finishing": "Befejezés",
    "Error": "Hiba",
    "Download was cancelled": "Letöltés visszavonva",
    "Cancel download failed": "Letöltés visszavonása sikertelen",
    "Record deleted": "Felvétel törölve",
    "Delete record failed": "Felvétel törlése sikertelen",


    // Init Modal

    "Share Initialization Wizard": "Megosztások kezdeti beállítása",
    "Welcome to CasaConnect": "Üdvözöl a CasaConnect",
    "With this feature you can easily create peer-to-peer file sharing transfers between you and your friends.": "A CasaConnect segítségével könnyen létrehozhatsz peer-to-peer fájlmegosztást saját magad és barátod között.",
    "You need to do some simple setup.": "El kell végezned néhány egyszerű beállítást.",
    "Let's Start": "Vágjunk bele!",
    "Share-Account": "Fiók",
    "Share-Setting": "Beállítások",
    "Share-Recommend": "Ajánlások",
    "Share-Finish": "Befejezés",
    "Nickname": "Név",
    "Please enter your nickname.": "Adj meg egy becenevet.",
    "Description": "Leírás",
    "Please enter your Description.": "Adj meg leírást.",
    "Shared folders": "Megosztott mappák",
    "Default download path": "Alapértelmezett letöltési útvonal",
    "Need to add at least one directory.": "Legalább egy könyvtár létrehozása szükséges.",
    "Change": "Módosítás",
    "We have prepared some public servers.": "Elkészítettünk néhány nyilvános szervert.",
    "You need to choose one of them to start with.": "Válassz egyet a kezdéshez.",
    "At least one must be selected.": "Legalább egyet szükséges választani a kezdéshez.",
    "Share is ready!": "A megosztás elkészült!",
    "You have completed the initial setup.": "Befejezted a kezdeti beállításokat.",
    "Next you can follow the use guide to learn how to use it.": "A továbbiakban a használati útmutatót követve megismerheted a CasaConnect használatát.",
    "Share-Go": "Mehet",

    // Add Friend Modal
    "Send Friend Request": "Barátkérelem elküldése",
    "Friend's ID": "Barát azonosítója",
    "Please enter friend's Share ID.": "Add meg a barátod megosztási azonosítóját.",
    "Friend Request Sent.": "Barátkérelem elküldve.",
    "is already your friend.": "már a barátod.",

    // Download Modal
    "Download to": "{file} letöltése ide: ",
    "Download path": "Letöltési útvonal",
    "Set as default download path": "Beállítás alapértelmezett letöltési útvonalnak",
    "Download has started": "Letöltés elkezdése",
    "Download failed": "Letöltés sikertelen",

    // Remark Modal
    "Please enter the remark.": "Írj megjegyzést.",
    "Remark saved": "Megjegyzés mentve",
    "Remark save failed": "Megjegyzés mentése sikertelen",

    // Profile Modal 
    "Edit My Info": "Saját azonosító módosítása",
    "My ID": "Saját azonosító",
    "Update successful": "Sikeres frissítés",
    "Update failed": "Sikertelen frissítés",

}
