// Indonesian

export default {
    // Commons
    "": "",
    "OK": "OK",
    "Cancel": "Batal",
    "Submit": "Kirim",
    "Back": "Kembali",
    "Edit": "Edit",
    "Update": "Perbarui",
    "Create": "Buat",
    "Next": "Berikutnya",
    "Close": "Tutup",
    "Select": "Pilih",
    "Save": "Simpan",
    "Add": "Tambah",
    "Go": "Lanjut",
    "Import": "Impor",
    "Low": "Rendah",
    "Medium": "Sedang",
    "High": "Tinggi",
    "Language": "Bahasa",
    "Change": "Ubah",
    "Start": "Mulai",

    "This field is required": "Kolom ini wajib diisi",
    "This field must be a valid email": "Kolom ini harus berupa email yang valid",
    "This field confirmation does not match": "Konfirmasi kolom ini tidak cocok",
    "This field must have 2 options": "Kolom ini harus memiliki 2 pilihan",
    "This field must have more than 5 characters": "Kolom ini harus memiliki lebih dari 5 karakter",
    "You entered an invalid RFC1123 hostname": "Nama host RFC1123 yang Anda masukkan tidak valid",

    // Init Page
    "Welcome to CasaOS": "Selamat datang di CasaOS",
    "Let's create your initial account": "Mari buat akun utama Anda",
    "Go →": "Lanjut →",
    "Create Account": "Buat Akun",
    "Username": "Nama Pengguna",
    "Confirm Password": "Konfirmasi Kata Sandi",
    "Username or Password error!": "Nama pengguna atau Kata Sandi salah!",
    "All things done!": "Semua selesai!",


    // Login
    "Login": "Masuk",
    "Password error!": "Kata sandi salah!",

    // Account
    "Account": "Akun",
    "Logout": "Keluar",
    "Name": "Nama",
    "Password": "Kata Sandi",
    "Change name": "Ubah nama",
    "Change Password": "Ubah Kata Sandi",
    "Original password": "Kata sandi lama",
    "New password": "Kata sandi baru",
    "Confirm the new password again": "Konfirmasi kembali kata sandi baru",

    // Dashboard Settings
    "Settings": "Pengaturan",
    "Dashboard Setting": "Pengaturan Dasbor",
    "Search Engine": "Mesin Pencari",
    "WebUI Port": "Port WebUI",
    "Currently the latest version": "Saat ini adalah versi terbaru",
    "A new version is available!": "Versi baru tersedia!",
    "Edit Web UI port": "Edit port WebUI",
    "Automount USB Drive": "Pasang Otomatis Drive USB",
    "Wallpaper": "Wallpaper",
    "Change wallpaper": "Ubah wallpaper",
    "Show Search Bar": "Tampilkan Bilah Pencarian",
    "Show Recommended Apps": "Tampilkan Aplikasi Rekomendasi",
    "Upgrade Now": "Perbarui Sekarang",
    "Enabling this function may cause boot failures when the Raspberry Pi device is booted from USB": "Mengaktifkan fungsi ini dapat menyebabkan kegagalan booting pada perangkat Raspberry Pi saat melakukan booting dari USB",

    // Terminal & Logs
    "Terminal & Logs": "Terminal & Log",
    "Terminal": "Terminal",
    "Logs": "Log",

    // Widgets
    "Widgets Settings": "Pengaturan Widget",
    "Time": "Waktu",
    "Cores": "Inti (Core)",
    "System Status": "Status Sistem",
    "Storage Status": "Status Penyimpanan",
    "Network Status": "Status Jaringan",
    "available of": "{avl} tersedia dari {total}",

    // Search 
    "Search...": "Cari...",

    // Sync
    "Sync your data": "Sinkronkan data Anda",
    "Use Syncthing to sync your files between multiple devices.": "Gunakan Syncthing untuk menyinkronkan berkas di berbagai perangkat.",
    "Install": "Instal",
    "Config": "Konfigurasi",
    "Total": "Total",
    "Failed to start, please try again.": "Gagal memulai, silakan coba lagi.",
    "Syncthing is not running, start it?": "Syncthing tidak berjalan, mulai sekarang?",
    "Starting Syncthing...": "Memulai Syncthing...",

    // Iot
    "Have an idea? Shoot it on Discord!": "Punya ide? Sampaikan di Discord!",
    "Smarten up your home": "Buat rumah Anda lebih pintar",
    "We want to give you a smart home experience with privacy, high speed, and localized storage.": "Kami ingin memberikan pengalaman rumah pintar dengan privasi, kecepatan tinggi, dan penyimpanan lokal.",
    "In development": "Dalam pengembangan",

    // Apps
    "Apps": "Aplikasi",
    "App": "Aplikasi",
    "Open": "Buka",
    "Setting": "Pengaturan",
    "Uninstall": "Hapus Instalasi",
    "Attention": "Perhatian",
    "Data cannot be recovered after deletion! <br>Continue on to uninstall this application?": "Data tidak dapat dipulihkan setelah dihapus! <br>Lanjutkan untuk menghapus aplikasi ini?",
    "Featured Apps": "Aplikasi Unggulan",
    "Custom Install": "Instal Kustom",
    "Continue in background": "Lanjutkan di latar belakang",
    "Install a new App manually": "Instal aplikasi baru secara manual",
    "Docker Image": "Citra Docker (Image)",
    "App name": "Nama aplikasi",
    "Icon URL": "URL Ikon",
    "Network": "Jaringan",
    "Privileged": "Hak Istimewa (Privileged)",
    "Container Command": "Perintah Kontainer",
    "Container Capabilities (cap-add)": "Kapabilitas Kontainer (cap-add)",
    "Container Hostname": "Nama Host Kontainer",
    "Hostname of app container": "Nama host kontainer aplikasi",
    "Ports": "Port",
    "Volumes": "Volume",
    "Environment Variables": "Variabel Lingkungan",
    "Devices": "Perangkat",
    "Memory Limit": "Batas Memori",
    "CPU Shares": "Pangsa CPU",
    "Restart Policy": "Kebijakan Mulai Ulang",
    "App Description": "Deskripsi Aplikasi",
    "No ports now, click “+” to add one.": "Belum ada port, klik “+” untuk menambahkan.",
    "No volumes now, click “+” to add one.": "Belum ada volume, klik “+” untuk menambahkan.",
    "No environment variables now, click “+” to add one.": "Belum ada variabel lingkungan, klik “+” untuk menambahkan.",
    "No devices now, click “+” to add one.": "Belum ada perangkat, klik “+” untuk menambahkan.",
    "No commands now, click “+” to add one.": "Belum ada perintah, klik “+” untuk menambahkan.",
    "e.g.,hello-world:latest": "misal, hello-world:latest",
    "Your custom App Name": "Nama Aplikasi kustom Anda",
    "Your custom icon URL": "URL ikon kustom Anda",
    "Installing": "Menginstal",
    "Export AppFile": "Ekspor AppFile",
    "AppFile": "AppFile",
    "Drop your app file here or click to upload": "Letakkan file aplikasi di sini atau klik untuk mengunggah",
    "Host": "Host",
    "Container": "Kontainer",
    "Key": "Kunci (Key)",
    "Value": "Nilai (Value)",
    "Protocol": "Protokol",
    "This is not a valid json file.": "Ini bukan berkas JSON yang valid.",
    "Your browser does not support file reading.": "Browser Anda tidak mendukung pembacaan berkas.",
    "has been selected": "telah dipilih",
    "Please fill correct command line": "Harap isi baris perintah dengan benar",
    "Please import a valid App file": "Harap impor berkas aplikasi yang valid",
    "AutoFill only helps you to complete most of the configuration.": "Isi Otomatis hanya membantu Anda menyelesaikan sebagian besar konfigurasi.",
    "Some configuration information such as:": "Beberapa informasi konfigurasi seperti:",
    "the port and path of the Web UI": "port dan jalur Web UI",
    "the mount location of the volume or file": "lokasi pemasangan (mount) volume atau berkas",
    "the port mapping of the Host": "pemetaan port Host",
    "optional configuration items": "item konfigurasi opsional",
    "These include but are not limited to these cases and <b>still need to be confirmed or modified by you.</b>": "Hal ini mencakup namun tidak terbatas pada kasus-kasus tersebut dan <b>masih perlu dikonfirmasi atau dimodifikasi oleh Anda.</b>",
    "Feel free to suggest improvements to this feature in Discord Server!": "Jangan ragu untuk menyarankan peningkatan fitur ini di Server Discord!",
    "Using localhost or 127.0.0.1 will cause the application to be inaccessible, please use the real ip to access.": "Menggunakan localhost atau 127.0.0.1 akan menyebabkan aplikasi tidak dapat diakses, harap gunakan IP asli untuk mengakses.",
    "CATEGORY": "KATEGORI",
    "DEVELOPER": "PENGEMBANG",
    "REQUIRE": "PERSYARATAN",
    "MEMORY": "MEMORI",
    "DISK": "DISK",
    "App Store": "Toko Aplikasi",
    "Community Apps": "Aplikasi Komunitas",
    "From community contributors, not optimized for CasaOS, but provides a basic App experience.": "Dari kontributor komunitas, tidak dioptimalkan untuk CasaOS, tetapi menyediakan pengalaman aplikasi dasar.",
    "Sort by": "Urutkan berdasarkan",
    "Click icon to import.": "Klik ikon untuk mengimpor.",
    "Drag icons to sort.": "Tarik ikon untuk mengurutkan.",
    "Import to CasaOS": "Impor ke CasaOS",
    "Existing Docker Apps": "Aplikasi Docker yang Ada",
    "Port [Please add a ports set first]": "Port [Harap tambahkan set port terlebih dahulu]",
    "[Optional]": "[Opsional]",
    "Notice: If there are multiple services, only the first set can be analyzed correctly": "Catatan: Jika terdapat banyak layanan, hanya set pertama yang dapat dianalisis dengan benar",
    "There was an error loading the data, please try again!": "Terjadi kesalahan saat memuat data, silakan coba lagi!",

    //Storage
    "Create Storage": "Buat Penyimpanan",
    "Storage Manager": "Manajer Penyimpanan",
    "Storage": "Penyimpanan",
    "Drive": "Drive",
    "Single Drive Storage": "Penyimpanan Drive Tunggal",
    "Format": "Format",
    "Remove": "Hapus",
    "Available Total": "{name} | Tersedia: {avl} (Total: {total})",
    "Health": "Kesehatan",
    "Healthy": "Sehat",
    "Damage": "Rusak",
    "Temp": "Suhu",
    "WARNING!": "PERINGATAN!",
    "This selected drive will be emptied if there is data on it. Make sure again that there is no important data on the selected drive that has not been backed up. If there is data to be migrated, the related apps will be stopped during the migration process.": "Drive yang dipilih ini akan dikosongkan jika ada data di dalamnya. Pastikan kembali bahwa tidak ada data penting yang belum dicadangkan. Jika ada data yang akan dimigrasi, aplikasi terkait akan dihentikan selama proses migrasi.",
    "Creation in progress": "Sedang dalam pembuatan",
    "Apply": "Terapkan",
    "Just Mount": "Hanya Pasang (Mount)",
    "Storage Name": "Nama Penyimpanan",
    "Choose Drive": "Pilih Drive",
    "Enter the password to continue:": "Masukkan kata sandi untuk melanjutkan:",
    "Used": "Digunakan",
    "CasaOS reserves 1% of file space when creating storage in EXT4 format.": "CasaOS mencadangkan 1% ruang berkas saat membuat penyimpanan dalam format EXT4.",
    "The selected drive will be emptied.": "Drive yang dipilih akan dikosongkan.",
    "Please make sure again that there is no important data on the selected drive that needs to be backed up.": "Harap pastikan kembali bahwa tidak ada data penting pada drive terpilih yang perlu dicadangkan.",
    "The drive you select can be used directly as storage.": "Drive yang Anda pilih dapat digunakan langsung sebagai penyimpanan.",
    "You can also choose to create it after formatting. If formatted, the selected drive will be emptied.": "Anda juga dapat memilih untuk membuatnya setelah diformat. Jika diformat, drive yang dipilih akan dikosongkan.",
    "Format and Create": "Format dan Buat",

    // Feedback
    "Join Discord": "Bergabung ke Discord",
    "Visit our Github": "Kunjungi Github kami",
    "Bug report": "Laporan Bug",
    "Title": "Judul",
    "Describe the bug": "Jelaskan bug tersebut",
    "A clear and concise description of what the bug is.": "Deskripsi yang jelas dan singkat mengenai apa bug tersebut.",
    "System infomation": "Informasi sistem",

    // Files
    "Files": "Berkas",
    "Upload or Create": "Unggah atau Buat",
    "Upload Files": "Unggah Berkas",
    "Upload Folder": "Unggah Folder",
    "New Folder": "Folder Baru",
    "New File": "Berkas Baru",
    "Change View": "Ubah Tampilan",
    "Upload to": "Unggah ke",
    "Uploading": "Mengunggah",
    "Completed": "Selesai",
    "success": "Berhasil",
    "error": "Kesalahan",
    "uploading": "mengunggah",
    "paused": "ditangguhkan",
    "waiting": "menunggu",
    "Download": "Unduh",
    "Copy Path": "Salin Jalur",
    "Rename": "Ganti Nama",
    "Cut": "Potong",
    "Copy": "Salin",
    "Delete": "Hapus",
    "Are you sure?": "Apakah Anda yakin?",
    "Paste": "Tempel",
    "Refresh": "Segarkan",
    "Code Editor": "Editor Kode",
    "Saved": "Tersimpan",
    "Want to save?": "Ingin menyimpan?",
    "Your changes will be lost if you don’t save them.": "Perubahan Anda akan hilang jika tidak disimpan.",
    "Don’t Save": "Jangan Simpan",
    "Drop your files here to upload": "Letakkan berkas di sini untuk mengunggah",
    "or": "atau",
    "Date Modified": "Tanggal Diubah",
    "Size": "Ukuran",
    "Play in IINA": "Putar di IINA",
    "Play in PotPlayer": "Putar di PotPlayer",
    "Play in VLC": "Putar di VLC",
    "Download in preparation...": "Menyiapkan unduhan...",
    "Copied to clipboard": "Tersalin ke papan klip",
    "Previous": "Sebelumnya",
    "Zoom in": "Perbesar",
    "Rotate": "Putar",
    "Reset": "Atur Ulang",
    "Zoom out": "Perkecil",
    "INext": "Berikutnya",
    "Move": "Pindah",
    "Current Tasks": "Tugas Saat Ini",
    "Deleting files": "Menghapus berkas",
    "Are you sure you want to <b>delete</b> these files? This action cannot be undone.": "Apakah Anda yakin ingin <b>menghapus</b> berkas-berkas ini? Tindakan ini tidak dapat dibatalkan.",
    "select-items": "Pilih {num} item",
    "total-items": "Total {num} item",
    "cancel-all": "Batalkan Semua",
    "Paste - Overwrite": "Tempel - Timpa",
    "Paste - Skip": "Tempel - Lewati",
    "Set as wallpaper": "Atur sebagai wallpaper",
    "Set wallpaper successfully.": "Berhasil mengatur wallpaper.",
    "Save failed, please try again!": "Gagal menyimpan, silakan coba lagi!",
    "Upload failed, please try again!": "Gagal mengunggah, silakan coba lagi!",

}
