// Italiano

export default {
    // Commons
    "": "",
    "OK": "OK",
    "Cancel": "Cancella",
    "Submit": "Invia",
    "Back": "Indietro",
    "Edit": "Modifica",
    "Update": "Aggiorna",
    "Create": "Crea",
    "Next": "Prossimo",
    "Close": "Chiudi",
    "Select": "Seleziona",
    "Save": "Salva",
    "Add": "Aggiungi",
    "Go": "Vai",
    "Import": "Importa",
    "Low": "Basso",
    "Medium": "Medio",
    "High": "Alto",
    "Language": "Lingua",
    "Change": "Cambia",
    "Start": "Avvia",

    "This field is required": "Questo campo è obbligatorio",
    "This field must be a valid email": "Questo campo deve avere un e-mail valida",
    "This field confirmation does not match": "La conferma di questo campo non corrisponde",
    "This field must have 2 options": "Questo campo deve avere 2 opzioni",
    "This field must have more than 5 characters": "Questo campo deve contenere più di 5 caratteri",
    "You entered an invalid RFC1123 hostname": "Hai inserito un nome host RFC1123 invalido",

    // Init Page
    "Welcome to CasaOS": "Benvenuto in CasaOS",
    "Let's create your initial account": "Creiamo il tuo primo account",
    "Go →": "Vai →",
    "Create Account": "Crea Account",
    "Username": "Nome Utente",
    "Confirm Password": "Conferma Password",
    "Username or Password error!": "Nome utente o password errati!",
    "All things done!": "Tutto fatto!",


    // Login
    "Login": "Login",
    "Password error!": "Password errata!",

    // Account
    "Account": "Account",
    "Logout": "Logout",
    "Name": "Nome",
    "Password": "Password",
    "Change name": "Cambia Nome",
    "Change Password": "Cambia Password",
    "Original password": "Password originale",
    "New password": "Nuova password",
    "Confirm the new password again": "Conferma di nuovo la nuova password",

    // Dashboard Settings
    "Settings": "Impostazioni",
    "Dashboard Setting": "Impostazione della Dashboard",
    "Search Engine": "Motore di ricerca",
    "WebUI port": "Porta WebUI",
    "Currently the latest version": "Attualmente l'ultima versione",
    "A new version is available!": "È disponibile una nuova versione!",
    "Edit Web UI port": "Modifica porta WebUI",
    "Automount USB Drive": "Monta in automatico dischi USB",
    "Wallpaper": "Sfondo",
    "Change wallpaper": "Cambia sfondo",
    "Show Search Bar": "Mostra barra di ricerca",
    "Show Recommended Apps": "Mostra app raccomandate",
    "Upgrade Now": "Aggiorna ora",
    "Enabling this function may cause boot failures when the Raspberry Pi device is booted from USB": "Attivare questa funzione può causare errori di avvio quando il Raspberry Pi si avvia da USB",
    // Terminal & Logs
    "Terminal & Logs": "Terminale & Log",
    "Terminal": "Terminale",
    "Logs": "Log",

    // Widgets
    "Widgets Settings": "Impostazioni widget",
    "Time": "Data e ora",
    "Cores": "Cores",
    "System Status": "Stato del sistema",
    "Storage Status": "Stato archiviazione",
    "Network Status": "Stato della rete",
    "available of": "{avl} disponibile di {total}",

    // Search 
    "Search...": "Cerca...",

    // Sync
    "Sync your data": "Sincronizza i tuoi dati",
    "Use Syncthing to sync your files between multiple devices.": "Usa Syncthing per sincronizzare i tuoi file tra più dispositivi.",
    "Total": "Totale",
    "Install": "Installa",
    "Config": "Configura",
    "Failed to start, please try again.": "Errore nell'avvio, riprova.",
    "Syncthing is not running, start it?": "Syncthing non è avviato, avviarlo?",
    "Starting Syncthing...": "Avviando Syncthing...",

    // Iot
    "Have an idea? Shoot it on Discord!": "Hai un'idea? Girala su Discord!",
    "Smarten up your home": "Rendi più Smart la tua casa",
    "We want to give you a smart home experience with privacy, high speed, and localized storage.": "Vogliamo offrirti un'esperienza di casa intelligente con privacy, alta velocità e spazio di archiviazione localizzato.",
    "In development": "In sviluppo",

    // Apps
    "Apps": "Apps",
    "App": "App",
    "Open": "Apri",
    "Setting": "Impostazioni",
    "Uninstall": "Disinstalla",
    "Attention": "Attenzione",
    "Data cannot be recovered after deletion! <br>Continue on to uninstall this application?": "I dati non possono essere recuperati dopo la cancellazione! <br>Continuare a disinstallare questa applicazione?",
    "Featured Apps": "App in evidenza",
    "Custom Install": "Installazione personalizzata",
    "Continue in background": "Continua in background",
    "Install a new App manually": "Installa una nuova app manualmente",
    "Docker Image": "Immagine Docker",
    "App name": "Nome App",
    "Icon URL": "Icona URL",
    "Network": "Rete",
    "Privileged": "Privilegiato",
    "Container Command": "Container Command",
    "Container Capabilities (cap-add)": "Container Capabilities (cap-add)",
    "Container Hostname": "Container Hostname",
    "Hostname of app container": "Hostname of app container",
    "Ports": "Porte",
    "Volumes": "Volumi",
    "Environment Variables": "Variabili d'ambiente",
    "Devices": "Dispositivi",
    "Memory Limit": "Limite di memoria",
    "CPU Shares": "CPU condivise",
    "Restart Policy": "Policy di riavvio",
    "App Description": "Descrizione dell'App",
    "No ports now, click “+” to add one.": "Nessuna porta ora, fai clic su “+” per aggiungerne una.",
    "No volumes now, click “+” to add one.": "Nessun volume ora, fai clic su “+” per aggiungerne uno.",
    "No environment variables now, click “+” to add one.": "Nessuna variabile d'ambiente ora, fai clic su “+” per aggiungerne una.",
    "No devices now, click “+” to add one.": "Nessun dispositivo ora, fai clic su “+” per aggiungerne uno.",
    "No commands now, click “+” to add one.": "Nessun comando ora, fai clic su “+” per aggiungerne uno.",
    "e.g.,hello-world:latest": "ad es.,hello-world:più recente",
    "Your custom App Name": "Il nome della tua app personalizzata",
    "Your custom icon URL": "La tua icona personalizzata URL",
    "Installing": "Installazione",
    "Export AppFile": "Esporta FileApp",
    "AppFile": "FileApp",
    "Drop your app file here or click to upload": "Trascina qui il file dell'app o fai clic per caricarlo",
    "Host": "Host",
    "Container": "Container",
    "Key": "Chiave",
    "Value": "Valore",
    "Protocol": "Protocollo",
    "This is not a valid json file.": "Questo non è un file json valido.",
    "Your browser does not support file reading.": "Il tuo browser non supporta la lettura dei file.",
    "has been selected": "è stato selezionato",
    "Please fill correct command line": "Si prega di compilare la riga di comando corretta",
    "Please import a valid App file": "Si prega di importare un file App valido",
    "AutoFill only helps you to complete most of the configuration.": "La compilazione automatica ti aiuta solo a completare la maggior parte della configurazione.",
    "Some configuration information such as:": "Alcune informazioni di configurazione come:",
    "the port and path of the Web UI": "la porta e il percorso dell'interfaccia utente Web",
    "the mount location of the volume or file": "la posizione di montaggio del volume o del file",
    "the port mapping of the Host": "la mappatura delle porte dell'host",
    "optional configuration items": "elementi di configurazione opzionali",
    "These include but are not limited to these cases and <b>still need to be confirmed or modified by you.</b>": "Questi includono ma non sono limitati a questi casi e <b> devono ancora essere confermati o modificati da te.</b>",
    "Feel free to suggest improvements to this feature in Discord Server!": "Sentiti libero di suggerire miglioramenti a questa funzione in Discord Server!",
    "Using localhost or 127.0.0.1 will cause the application to be inaccessible, please use the real ip to access.": "L'utilizzo di localhost o 127.0.0.1 renderà l'applicazione inaccessibile, utilizzare l'ip reale per accedere.",
    "CATEGORY": "CATEGORIA",
    "DEVELOPER": "SVILUPPATORE",
    "REQUIRE": "RICHIEDERE",
    "MEMORY": "MEMORIA",
    "DISK": "DISCO",
    "App Store": "App Store",
    "Community Apps": "App della Comunità",
    "From community contributors, not optimized for CasaOS, but provides a basic App experience.": "Da contributori della community, non ottimizzato per CasaOS, ma fornisce un'esperienza di base dell'app.",
    "Sort by": "Ordina per",
    "Click icon to import.": "Fai click sull'icona per importarla.",
    "Drag icons to sort.": "Trascina le icone per ordinarle.",
    "Import to CasaOS": "Importa in CasaOS",
    "Existing Docker Apps": "App Docker esistente",
    "Port [Please add a ports set first]": "Porta [Aggiungi prima un set di porte]",
    "[Optional]": "[Opzionale]",
    "Notice: If there are multiple services, only the first set can be analyzed correctly": "Nota: se ci sono più servizi, solo il primo set viene analizzato correttamente",
    "There was an error loading the data, please try again!":"C'è stato un errore caricando i dati, riprova!",


    //Storage
    "Create Storage": "Crea archiviazione",
    "Storage Manager": "Manager archiviazione",
    "Storage": "Archiviazione",
    "Drive": "Disco",
    "Single Drive Storage": "Archiviazione su singolo disco",
    "Format": "Formato",
    "Remove": "Rimuovi",
    "Available Total": "{name} | Disponibile: {avl} (Totale: {total})",
    "Health": "Salute",
    "Healthy": "A posto",
    "Damage": "Danno",
    "Temp": "Temp",
    "WARNING!": "ATTENZIONE!",
    "This selected drive will be emptied if there is data on it. Make sure again that there is no important data on the selected drive that has not been backed up. If there is data to be migrated, the related apps will be stopped during the migration process.": "Questo disco selezionato sarà svuotato di tutti i dati. Assicurati che non ci siano dati importanti che non sono stati backup-ati da qualche parte.",
    "Creation in progress": "Creazione in corso",
    "Apply": "Applica",
    "Just Mount": "Monta solo",
    "Storage Name": "Nome archiviazione",
    "Choose Drive": "Scegli disco",
    "Enter the password to continue:": "Inserisci la password per continuare:",
    "Used": "Usato",
    "CasaOS reserves 1% of file space when creating storage in EXT4 format.": "CasaOS riserva 1% di spazio quando crea la partizione in formato EXT4.",
    "The selected drive will be emptied.": "Il disco selezionato sarà svuotato.",
    "Please make sure again that there is no important data on the selected drive that needs to be backed up.": "Assicurati ancora che non ci siano dati importanti sul disco selezionato che devono essere salvati.",
    "The drive you select can be used directly as storage.": "Il disco selezionato può essere direttamente utilizzato come spazio di archiviazione",
    "You can also choose to create it after formatting. If formatted, the selected drive will be emptied.": "Puoi anche scegliere di crearlo dopo averlo formattato. Se formattato, il disco selezionato sarà svuotato.",
    "Format and Create": "Formatta e crea",

    // Feedback
    "Join Discord": "Accedi a Discord",
    "Visit our Github": "Visita il nostro Github",
    "Bug report": "Riporta un bug",
    "Title": "Titolo",
    "Describe the bug": "Descrivi l'errore",
    "A clear and concise description of what the bug is.": "Una descrizione chiara e concisa sull'errore.",
    "System infomation": "Informazioni sistema",

    // Files
    "Files": "Files",
    "Upload or Create": "Carica o crea",
    "Upload Files": "Carica Files",
    "Upload Folder": "Carica una cartella",
    "New Folder": "Nuova cartella",
    "New File": "Nuovo file",
    "Change View": "Cambia visualizzazione",
    "Upload to": "Carica su",
    "Uploading": "Caricamento",
    "Completed": "completato",
    "success": "Successo",
    "error": "Errore",
    "uploading": "caricamento",
    "paused": "In pausa",
    "waiting": "In attesa",
    "Download": "Download",
    "Copy Path": "Copia percorso",
    "Rename": "Rinomina",
    "Cut": "Taglia",
    "Copy": "Copia",
    "Delete": "Elimina",
    "Are you sure?": "Sei sicuro?",
    "Paste": "Incolla",
    "Refresh": "Aggiorna",
    "Code Editor": "Editor codice",
    "Saved": "Salvato",
    "Want to save?": "Vuoi salvare?",
    "Your changes will be lost if you don’t save them.": "Le tue modifiche saranno perse se non salvi.",
    "Don’t Save": "Non salvare",
    "Drop your files here to upload": "Lascia i tuoi file qua per caricarli",
    "or": "oppure",
    "Date Modified": "Data modificata",
    "Size": "Dimensione",
    "Play in IINA": "Riproduci con IINA",
    "Play in PotPlayer": "Riproduci con PotPlayer",
    "Play in VLC": "Riproduci con VLC",
    "Download in preparation...": "Download in preparazione...",
    "Copied to clipboard": "Copiato nella clipboard",
    "Previous": "Precedente",
    "Zoom in": "Zoom in",
    "Rotate": "Ruota",
    "Reset": "Reset",
    "Zoom out": "Zoom out",
    "INext": "Prossimo",
    "Move": "Muovi",
    "Current Tasks": "Lavoro corrente",
    "Deleting files": "Eliminando files",
    "Are you sure you want to <b>delete</b> these files? This action cannot be undone.": "Sei sicuri di voler <b>eliminare</b> questi file? Questa azione è irreversibile.",
    "select-items": "Seleziona {num} elementi",
    "total-items": "Totale {num} elementi",
    "cancel-all": "Cancella tutto",
    "Paste - Overwrite": "Incolla - Sovrascivi",
    "Paste - Skip": "Incolla - Salta",
    "Set as wallpaper": "Imposta come sfondo",
    "Set wallpaper successfully.": "Sfondo impostato con successo.",
    "Save failed, please try again!": "Salvataggio non riuscito, riprova!",
    "Upload failed, please try again!": "Upload fallito, riprova!",

}
