// English

export default {
    // Commons
    "": "",
    "OK": "확인",
    "Cancel": "취소",
    "Submit": "제출",
    "Back": "뒤로",
    "Edit": "편집",
    "Update": "업데이트",
    "Create": "생성",
    "Next": "다음",
    "Close": "닫기",
    "Select": "선택",
    "Save": "저장",
    "Add": "추가",
    "Go": "출발",
    "Import": "가져오기",
    "Low": "최소",
    "Medium": "중간",
    "High": "최고",
    "Language": "언어",

    "This field is required": "이 입력란은 필수입니다",
    "This field must be a valid email": "이 입력란은 유효한 이메일이어야 합니다",
    "This field confirmation does not match": "이 입력란 확인은 일치하지 않습니다",
    "This field must have 2 options": "이 입력란에는 2가지 옵션이 있어야 합니다",
    "This field must have more than 5 characters": "이 입력란은 5자 이상이어야 합니다",
    "You entered an invalid RFC1123 hostname": "잘못된 RFC1123 호스트 이름을 입력했습니다",

    // Init Page
    "Welcome to CasaOS": "CasaOS에 오신 걸 환영합니다",
    "Let's create your initial account": "이제 초기 계정을 생성해야 합니다",
    "Go →": "출발 →",
    "Create Account": "계정 생성",
    "Username": "사용자 이름",
    "Confirm Password": "암호 확인",
    "Username or Password error!": "사용자 이름 및 암호 오류!",
    "All things done!": "모든 작업 완료됨!",


    // Login
    "Login": "로그인",
    "Password error!": "암호 오류!",

    // Account
    "Account": "계정",
    "Logout": "로그아웃",
    "Name": "이름",
    "Password": "암호",
    "Change name": "이름 변경",
    "Change Password": "암호 변경",
    "Original password": "기존 암호",
    "New password": "새 암호",
    "Confirm the new password again": "새 비밀번호를 다시 확인하세요",

    // Dashboard Settings
    "Settings": "설정",
    "Dashboard Setting": "대시보드 구성",
    "Search Engine": "검색 엔진",
    "WebUI Port": "WebUI 포트",
    "Currently the latest version": "현재 최신 버전입니다",
    "A new version is available!": "새 버전을 사용할 수 있습니다!",
    "Edit Web UI port": "WebUI 포트 편집",
    "Automount USB Drive": "USB 드라이브 자동 마운트",
    "Upgrade Now": "지금 업그레이드",
    "Enabling this function may cause boot failures when the Raspberry Pi device is booted from USB": "이 기능을 활성화하면 USB에서 Raspberry Pi 장치를 부팅할 때 부팅 실패가 발생할 수 있습니다",

    // Terminal & Logs
    "Terminal & Logs": "터미널 및 로그",
    "Terminal": "터미널",
    "Logs": "로그",

    // Widgets
    "Widgets Settings": "위젯 설정",
    "Time": "시간",
    "Cores": "코어",
    "System Status": "시스템 상태",
    "Storage Status": "저장소 상태",
    "Network Status": "네트워크 상태",
    "available of": "{total} 중 {avl} 사용 가능",

    // Search 
    "Search...": "검색...",

    // Sync
    "Sync your data": "데이터 동기화",
    "Follow the guide to start syncing your files across multiple devices.": "가이드에 따라 여러 기기에서 파일 동기화를 시작하십시오.",
    "Go !": "출발 !",
    "Sync Guide": "동기화 가이드",
    "Install": "설치",
    "Config": "설정",
    "Complete": "완료",
    "Download Syncthing on the device you want to sync with CasaOS": "CasaOS와 동기화하려는 기기에 동기화 앱(Syncthing)을 다운로드합니다",
    "Get Syncthing for": "{os}용 동기화 앱(Syncthing) 내려받기",
    "Download APK": "APK 내려받기",
    "Show all Platforms": "모든 플랫폼 표시",
    'Install and open the downloaded application, then click the "Next" button.': '다운로드한 애플리케이션을 설치하고 연 후 "다음" 버튼을 클릭합니다.',
    "Device ID": "기기 식별자",
    "Fill in your Device ID to continue": "계속하려면 이 입력란에 기기 식별자를 입력하십시오",
    "How to get Device ID": "기기 식별자을 알아내는 방법",
    "What do I need to do on my device?": "내 기기에서 무엇을 해야 합니까?",
    "Open the SyncTrayzor": "SyncTrayzor을 엽니다",
    "Find the Device ID": "기기 식별자을 찾습니다",
    "Add new device on your device": "기기에 새 기기 추가",
    "Add new folder on your device": "기기에 새 폴더 추가",
    "Done!": "완료!",

    "Open Syncthing in the Launchpad": "Launchpad에서 동기화 앱(Syncthing)을 엽니다",
    "Find the Syncthing icon in the menubar": "메뉴 표시줄에서 동기화 앱(Syncthing) 아이콘을 찾습니다",
    "Open Syncthing": "동기화 앱(Syncthing)을 엽니다",
    "Open the menu": "메뉴을 엽니다",
    'Choose "Show device ID"': '"기기 식별자 표시"을 선택합니다',
    "Copy the Device ID": "기기 식별자을 복사합니다",
    "There you go!": "There you go!",
    "Your data has started to sync.It may take some minutes to fulfill synchronization.": "데이터 동기화가 시작되었습니다.<br>동기화를 완료하는 데 몇 분 정도 걸릴 수 있습니다.",
    "Up to Date": "최신 업데이트입니다",
    "Synchronizing": "동기화 중",
    "Synchronized": "동기화됨",
    "Total": "전체",
    "Add New Device": "새 기기 추가",

    // Iot
    "Have an idea? Shoot it on Discord!": "아이디어를 가지고 있나요? 디스코드에서 알려주세요!",
    "Smarten up your home": "Smarten up your home",
    "We want to give you a smart home experience with privacy, high speed, and localized storage.": "We want to give you a smart home experience with privacy, high speed, and localized storage.",
    "In development": "In development",

    // Apps
    "Apps": "앱",
    "App": "앱",
    "Open": "열기",
    "Setting": "설정",
    "Uninstall": "제거",
    "Attention": "Attention",
    "Data cannot be recovered after deletion! <br>Continue on to uninstall this application?": "삭제 후 데이터를 복구할 수 없습니다! <br>이 앱을 정말 삭제하시겠습니까?",
    "Featured Apps": "Featured Apps",
    "Custom Install": "커스텀 설치",
    "Continue in background": "백그라운드에서 계속 설치",
    "Install a new App manually": "Install a new App manually",
    "Docker Image": "도커 이미지",
    "App name": "앱 이름",
    "Icon URL": "아이콘 URL",
    "Network": "네트워크",
    "Privileged": "Privileged",
    "Container Command": "Container Command",
    "Container Capabilities (cap-add)": "Container Capabilities (cap-add)",
    "Container Hostname": "Container Hostname",
    "Hostname of app container": "Hostname of app container",
    "Ports": "포트",
    "Volumes": "볼륨",
    "Environment Variables": "환경 변수",
    "Devices": "장치",
    "Memory Limit": "메모리 제한",
    "CPU Shares": "CPU 공유",
    "Restart Policy": "정책 재시작",
    "App Description": "App Description",
    "No ports now, click “+” to add one.": "No ports now, click “+” to add one.",
    "No volumes now, click “+” to add one.": "No volumes now, click “+” to add one.",
    "No environment variables now, click “+” to add one.": "No environment variables now, click “+” to add one.",
    "No devices now, click “+” to add one.": "No devices now, click “+” to add one.",
    "No commands now, click “+” to add one.": "No commands now, click “+” to add one.",
    "e.g.,hello-world:latest": "e.g.,hello-world:latest",
    "Your custom App Name": "Your custom App Name",
    "Your custom icon URL": "Your custom icon URL",
    "Installing": "설치 중",
    "Export AppFile": "AppFile 내보내기",
    "AppFile": "AppFile",
    "Drop your app file here or click to upload": "Drop your app file here or click to upload",
    "Host": "Host",
    "Container": "Container",
    "Key": "Key",
    "Value": "Value",
    "Protocol": "Protocol",
    "This is not a valid json file.": "This is not a valid json file.",
    "Your browser does not support file reading.": "Your browser does not support file reading.",
    "has been selected": "has been selected",
    "Please fill correct command line": "Please fill correct command line",
    "Please import a valid App file": "Please import a valid App file",
    "AutoFill only helps you to complete most of the configuration.": "AutoFill only helps you to complete most of the configuration.",
    "Some configuration information such as:": "Some configuration information such as:",
    "the port and path of the Web UI": "the port and path of the Web UI",
    "the mount location of the volume or file": "the mount location of the volume or file",
    "the port mapping of the Host": "the port mapping of the Host",
    "optional configuration items": "optional configuration items",
    "These include but are not limited to these cases and <b>still need to be confirmed or modified by you.</b>": "These include but are not limited to these cases and <b>still need to be confirmed or modified by you.</b>",
    "Feel free to suggest improvements to this feature in Discord Server!": "Feel free to suggest improvements to this feature in Discord Server!",
    "Using localhost or 127.0.0.1 will cause the application to be inaccessible, please use the real ip to access.": "Using localhost or 127.0.0.1 will cause the application to be inaccessible, please use the real ip to access.",
    "CATEGORY": "CATEGORY",
    "DEVELOPER": "DEVELOPER",
    "REQUIRE": "REQUIRE",
    "MEMORY": "MEMORY",
    "DISK": "DISK",
    "App Store": "App Store",
    "Community Apps": "Community Apps",
    "From community contributors, not optimized for CasaOS, but provides a basic App experience.": "From community contributors, not optimized for CasaOS, but provides a basic App experience.",
    "Sort by": "Sort by",
    "Click icon to import apps into CasaOS": "Click icon to import apps into CasaOS",
    "Drag icons to sort": "Drag icons to sort",
    "Import to CasaOS": "Import to CasaOS",
    "Existing Docker Apps": "Existing Docker Apps",
    "Port [Please add a ports set first]": "Port [Please add a ports set first]",
    "[Optional]": "[Optional]",
    "Notice: If there are multiple services, only the first set can be analyzed correctly": "Notice: If there are multiple services, only the first set can be analyzed correctly",
    "No need": "No need",


    //Storage
    "Create Storage": "Create Storage",
    "Storage Manager": "Storage Manager",
    "Storage": "Storage",
    "Drive": "Drive",
    "Single Drive Storage": "Single Drive Storage",
    "Format": "Format",
    "Remove": "Remove",
    "Available Total": "{name} | Available: {avl} (Total: {total})",
    "Health": "Health",
    "Healthy": "Healthy",
    "Damage": "Damage",
    "Temp": "Temp",
    "WARNING!": "위험!",
    "This selected drive will be emptied if there is data on it. Make sure again that there is no important data on the selected drive that has not been backed up. If there is data to be migrated, the related apps will be stopped during the migration process.": "This selected drive will be emptied if there is data on it. Make sure again that there is no important data on the selected drive that has not been backed up. If there is data to be migrated, the related apps will be stopped during the migration process.",
    "Creation in progress": "Creation in progress",
    "Apply": "Apply",
    "Just Mount": "Just Mount",
    "Storage Name": "Storage Name",
    "Choose Drive": "Choose Drive",
    "Enter the password to continue:": "Enter the password to continue:",
    "Used": "Used",
    "CasaOS reserves 1% of file space when creating storage in EXT4 format.": "CasaOS reserves 1% of file space when creating storage in EXT4 format.",
    "The selected drive will be emptied.": "The selected drive will be emptied.",
    "Please make sure again that there is no important data on the selected drive that needs to be backed up.": "Please make sure again that there is no important data on the selected drive that needs to be backed up.",
    "The drive you select can be used directly as storage.": "The drive you select can be used directly as storage.",
    "You can also choose to create it after formatting. If formatted, the selected drive will be emptied.": "You can also choose to create it after formatting. If formatted, the selected drive will be emptied.",
    "Format and Create": "Format and Create",

    // Feedback
    "Join Discord": "디스코드 서버 입장",
    "Visit our Github": "우리의 깃허브 보기",
    "Bug report": "버그 제보",
    "Title": "제목",
    "Describe the bug": "버그 설명",
    "A clear and concise description of what the bug is.": "A clear and concise description of what the bug is.",
    "System infomation": "시스템 정보",

    // Files
    "Files": "파일",
    "Upload or Create": "업로드 또는 만들기",
    "Upload Files": "파일 업로드",
    "Upload Folder": "폴더 업로드",
    "New Folder": "새로운 폴더",
    "New File": "새로운 파일",
    "Change View": "보기 변경",
    "Upload to": "Upload to",
    "Uploading": "업로드중",
    "Completed": "완료",
    "success": "성공",
    "error": "에러",
    "uploading": "업로드중",
    "paused": "일시정지",
    "waiting": "기다리는중",
    "Download": "다운로드",
    "Copy Path": "경로 복사",
    "Rename": "이름변경",
    "Cut": "잘라내기",
    "Copy": "복사",
    "Delete": "삭제",
    "Are you sure?": "정말하시겠습니까?",
    "Paste": "붙여넣기",
    "Refresh": "새로고침",
    "Code Editor": "코드 에디터",
    "Saved": "저장됨",
    "Want to save?": "저장하시겠습니까?",
    "Your changes will be lost if you don’t save them.": "Your changes will be lost if you don't save them.",
    "Don’t Save": "저장하지 않음",
    "Drop your files here to upload": "드래그 앤 드롭으로 파일 업로드",
    "or": "or",
    "Date Modified": "수정 날자",
    "Size": "크기",
    "Play in IINA": "IINA에서 플레이",
    "Play in PotPlayer": "PotPlayer에서 플레이",
    "Play in VLC": "VLC에서 플레이",
    "Download in preparation...": "Download in preparation...",
    "Copied to clipboard": "클립보드에 복사하였습니다",
    "Previous": "Previous",
    "Zoom in": "확대",
    "Rotate": "회전",
    "Reset": "리셋",
    "Zoom out": "축소",
    "INext": "Next",

    /* ******************************
    * Share Section
    ********************************/
    "Share module name": "CasaConnect",
    // Main
    "More info": "More info",
    "Edit Info": "Edit Info",
    "Copy My Share ID": "Copy My Share ID",
    "Add Friend": "친구 추가",
    "Friends": "친구",
    "Downloads": "다운로드",
    "Notification": "알림",
    "Upload not supported!": "업로드를 지원하지 않습니다!",
    "Select a friend to view his share.": "Select a friend to view his share.", //
    "There are no files in the current folder.": "There are no files in the current folder.",
    "has been copied to the clipboard": "has been copied to the clipboard",
    "is offline": "is offline",
    "Home": "Home",
    "Forward": "Forward",
    // User Context
    "Edit remark": "Edit remark",
    "Unblock this friend": "Unblock this friend",
    "Block this friend": "Block this friend",
    "Delete friend": "Delete friend",
    "Blocked this friend": "Blocked this friend",
    "Unblocked this friend": "Unblocked this friend",
    "Blocked failed": "Blocked failed",
    "Deleted this friend": "Deleted this friend",
    "Delete failed": "Delete failed",
    "Copy friend's ID": "Copy friend's ID",

    // Tour
    "Skip": "스킵",
    "Prev": "다음",
    "Let's Go": "Let's Go",
    "Here is your avatar, where you can change your personal information and get your ID to share with your friends.": "Here is your avatar, where you can change your personal information and get your ID to share with your friends.",
    "Click \"+\" and enter your friend's ID to send a friend request.": "Click \"+\" and enter your friend's ID to send a friend request.",
    "Browse your download progress and download history here.": "Browse your download progress and download history here.",
    "Modify your shared folders, and default download path here.": "Modify your shared folders, and default download path here.",
    "Well, let's start using it!": "Well, let's start using it!",

    // Download List
    "Downloading": "Downloading",
    "D-Completed": "Completed",
    "D-Total": "Total",
    "D-Name": "Name",
    "D-Size": "Size",
    "D-Progress": "Progress",
    "D-Retry": "Retry",
    "Cancel Download": "Cancel Download",
    "Delete this record": "Delete this record",
    "Finishing": "Finishing",
    "Error": "Error",
    "Download was cancelled": "Download was cancelled",
    "Cancel download failed": "Cancel download failed",
    "Record deleted": "Record deleted",
    "Delete record failed": "Delete record failed",


    // Init Modal

    "Share Initialization Wizard": "Share Initialization Wizard",
    "Welcome to CasaConnect": "Welcome to CasaConnect",
    "With this feature you can easily create peer-to-peer file sharing transfers between you and your friends.": "With this feature you can easily create peer-to-peer file sharing transfers between you and your friends.",
    "You need to do some simple setup.": "You need to do some simple setup.",
    "Let's Start": "Let's Start",
    "Share-Account": "Account",
    "Share-Setting": "Setting",
    "Share-Recommend": "Recommend",
    "Share-Finish": "Finish",
    "Nickname": "Name",
    "Please enter your nickname.": "Please enter your nickname.",
    "Description": "Description",
    "Please enter your Description.": "Please enter your Description.",
    "Shared folders": "Shared folders",
    "Default download path": "Default download path",
    "Need to add at least one directory.": "Need to add at least one directory.",
    "Change": "Change",
    "We have prepared some public servers.": "We have prepared some public servers.",
    "You need to choose one of them to start with.": "You need to choose one of them to start with.",
    "At least one must be selected.": "At least one must be selected.",
    "Share is ready!": "Share is ready!",
    "You have completed the initial setup.": "You have completed the initial setup.",
    "Next you can follow the use guide to learn how to use it.": "Next you can follow the use guide to learn how to use it.",
    "Share-Go": "Go",

    // Add Friend Modal
    "Send Friend Request": "Send Friend Request",
    "Friend's ID": "Friend's ID",
    "Please enter friend's Share ID.": "Please enter friend's Share ID.",
    "Friend Request Sent.": "Friend Request Sent.",
    "is already your friend.": "is already your friend.",

    // Download Modal
    "Download to": "Download {file} to",
    "Download path": "Download path",
    "Set as default download path": "Set as default download path",
    "Download has started": "Download has started",
    "Download failed": "다운로드 실패",

    // Remark Modal
    "Please enter the remark.": "Please enter the remark.",
    "Remark saved": "Remark saved",
    "Remark save failed": "Remark save failed",

    // Profile Modal 
    "Edit My Info": "내 정보 수정",
    "My ID": "내 ID",
    "Update successful": "업데이트 성공",
    "Update failed": "업데이트 실패",

}
