// Polish

export default {
    // Commons
    "": "",
    "OK": "OK",
    "Cancel": "Anuluj",
    "Submit": "Prześlij",
    "Back": "Powrót",
    "Edit": "Edytuj",
    "Update": "Aktualizuj",
    "Create": "Utwórz",
    "Next": "Dalej",
    "Close": "Zamknij",
    "Select": "Wybierz",
    "Save": "Zapisz",
    "Add": "Dodaj",
    "Go": "Idź",
    "Import": "Import",
    "Low": "Niski",
    "Medium": "Średni",
    "High": "Wysoki",
    "Language": "Język",

    "This field is required": "To pole jest wymagane",
    "This field must be a valid email": "W tym polu musi znajdować się prawidłowy adres e-mail",
    "This field confirmation does not match": "To potwierdzenie nie jest zgodne",
    "This field must have 2 options": "To pole musi mieć 2 opcje",
    "This field must have more than 5 characters": "To pole musi mieć więcej niż 5 znaków",

    // Init Page
    "Welcome to CasaOS": "Witamy w CasaOS",
    "Let's create your initial account": "Załóż swoje pierwsze konto",
    "Go →": "Idź →",
    "Create Account": "Utwórz konto",
    "Username": "Nazwa użytkownika",
    "Confirm Password": "Potwierdź hasło",
    "Username or Password error!": "Błąd nazwy użytkownika lub hasła!",
    "All things done!": "Wszystko gotowe!",


    // Login
    "Login": "Logowanie",
    "Password error!": "Błąd hasła!",

    // Account
    "Account": "Konto użytkownika",
    "Logout": "Wyloguj",
    "Name": "Użytkownik",
    "Password": "Hasło",
    "Change name": "Zmiana nazwy użytkownika",
    "Change Password": "Zmiana hasła",
    "Original password": "Dotychczasowe hasło",
    "New password": "Nowe hasło",
    "Confirm the new password again": "Ponownie potwierdź nowe hasło",

    // Dashboard Settings
    "Settings": "Ustawienia",
    "Dashboard Setting": "Ustawienia panelu kontrolnego",
    "Search Engine": "Wyszukiwarka",
    "WebUI Port": "Port interfejsu WebUI",
    "Currently the latest version": "Aktualnie najnowsza wersja",
    "A new version is available!": "Dostępna jest nowa wersja!",
    "Edit Web UI port": "Edycja portu WebUI",

    // Terminal & Logs
    "Terminal & Logs": "Terminal i logi",
    "Terminal": "Terminal",
    "Logs": "Logi",

    // Widgets
    "Widgets Settings": "Ustawienia widgetów",
    "Time": "Time",
    "System Status": "Stan systemu",
    "Disk Status": "Stan dysku",
    "Network Status": "Stan sieci",
    "available of": "{avl} dostępny z {total}",

    // Search 
    "Search...": "Szukaj...",

    // Sync
    "Sync your data": "Zsynchronizuj swoje dane",
    "Follow the guide to start syncing your files across multiple devices.": "Postępuj zgodnie z instrukcją, aby rozpocząć synchronizację plików na wielu urządzeniach.",
    "Go !": "Idź!",
    "Sync Guide": "Podręcznik synchronizacji",
    "Install": "Zainstaluj",
    "Config": "Konfiguracja",
    "Complete": "Zakończenie",
    "Download Syncthing on the device you want to sync with CasaOS": "Pobierz Syncthing na urządzenie, które chcesz zsynchronizować z CasaOS",
    "Get Syncthing for": "Pobierz Syncthing dla {os}",
    "Download APK": "Pobierz APK",
    "Show all Platforms": "Pokaż wszystkie platformy",
    'Install and open the downloaded application, then click the "Next" button.': 'Zainstaluj i otwórz pobraną aplikację, a następnie kliknij przycisk "Dalej".',
    "Device ID": "ID urządzenia",
    "Fill in your Device ID to continue": "Uzupełnij ID urządzenia, aby kontynuować",
    "How to get Device ID": "Jak uzyskać ID urządzenia",
    "What do I need to do on my device?": "Co muszę zrobić na moim urządzeniu?",
    "Open the SyncTrayzor": "Otwórz SyncTrayzor",
    "Find the Device ID": "Znajdź ID urządzenia",
    "Add new device on your device": "Dodaj nowe urządzenie na swoim urządzeniu",
    "Add new folder on your device": "Dodaj nowy folder na swoim urządzeniu",
    "Done!": "Gotowe!",

    "Open Syncthing in the Launchpad": "Otwórz Syncthing w Launchpad",
    "Find the Syncthing icon in the menubar": "Znajdź ikonę Syncthing w menubar.",
    "Open Syncthing": "Open Syncthing",
    "Open the menu": "Otwórz menu",
    'Choose "Show device ID"': 'Wybierz "Pokaż ID urządzenia"',
    "Copy the Device ID": "Skopiuj ID urządzenia",
    "There you go!": "Proszę bardzo!",
    "Your data has started to sync.It may take some minutes to fulfill synchronization.": "Twoje dane zaczęły się synchronizować.<br>Synchronizacja może potrwać kilka minut.",
    "Up to Date": "Aktualne",
    "Synchronizing": "Synchronizacja",
    "Synchronized": "Dane zsynchronizowane",
    "Total": "Razem",
    "Add New Device": "Dodaj nowe urządzenie",

    // Iot
    "Have an idea? Shoot it on Discord!": "Masz pomysł? Przedstaw go na Discord!",
    "Smarten up your home": "Inteligentny dom",
    "We want to give you a smart home experience with privacy, high speed, and localized storage.": "Chcemy dać Ci możliwość korzystania z inteligentnego domu z prywatnością, dużą prędkością i lokalną infrastrukturą dyskową.",
    "In development": "W przygotowaniu",

    // Apps
    "Apps": "Apps",
    "App": "App",
    "Open": "Open",
    "Setting": "Setting",
    "Uninstall": "Uninstall",
    "Attention": "Attention",
    "Data cannot be recovered after deletion! <br>Continue on to uninstall this application?": "Data cannot be recovered after deletion! <br>Continue on to uninstall this application?",
    "Featured Apps": "Featured Apps",
    "Custom Install": "Custom Install",
    "Continue in background": "Continue in background",
    "Install a new App manually": "Install a new App manually",
    "Docker Image": "Docker Image",
    "App name": "App name",
    "Icon URL": "Icon URL",
    "Network": "Network",
    "Ports": "Ports",
    "Volumes": "Volumes",
    "Environment Variables": "Environment Variables",
    "Devices": "Devices",
    "Memory Limit": "Memory Limit",
    "CPU Shares": "CPU Shares",
    "Restart Policy": "Restart Policy",
    "App Description": "App Description",
    "No ports now, click “+” to add one.": "No ports now, click “+” to add one.",
    "No volumes now, click “+” to add one.": "No volumes now, click “+” to add one.",
    "No environment variables now, click “+” to add one.": "No environment variables now, click “+” to add one.",
    "No devices now, click “+” to add one.": "No devices now, click “+” to add one.",
    "e.g.,hello-world:latest": "e.g.,hello-world:latest",
    "Your custom App Name": "Your custom App Name",
    "Your custom icon URL": "Your custom icon URL",
    "Installing": "Installing",
    "Export AppFile": "Export AppFile",
    "AppFile": "AppFile",
    "Drop your app file here or click to upload": "Drop your app file here or click to upload",
    "Host": "Host",
    "Container": "Container",
    "Key": "Key",
    "Value": "Value",
    "Protocol": "Protocol",
    "This is not a valid json file.": "This is not a valid json file.",
    "Your browser does not support file reading.": "Your browser does not support file reading.",
    "has been selected": "has been selected",
    "Please fill correct command line": "Please fill correct command line",
    "Please import a valid App file": "Please import a valid App file",
    "AutoFill only helps you to complete most of the configuration.": "AutoFill only helps you to complete most of the configuration.",
    "Some configuration information such as:": "Some configuration information such as:",
    "the port and path of the Web UI": "the port and path of the Web UI",
    "the mount location of the volume or file": "the mount location of the volume or file",
    "the port mapping of the Host": "the port mapping of the Host",
    "optional configuration items": "optional configuration items",
    "These include but are not limited to these cases and <b>still need to be confirmed or modified by you.</b>": "These include but are not limited to these cases and <b>still need to be confirmed or modified by you.</b>",
    "Feel free to suggest improvements to this feature in Discord Server!": "Feel free to suggest improvements to this feature in Discord Server!",
    "Using localhost or 127.0.0.1 will cause the application to be inaccessible, please use the real ip to access.": "Using localhost or 127.0.0.1 will cause the application to be inaccessible, please use the real ip to access.",
    "CATEGORY": "CATEGORY",
    "DEVELOPER": "DEVELOPER",
    "REQUIRE": "REQUIRE",
    "MEMORY": "MEMORY",
    "DISK": "DISK",
    "App Store": "App Store",
    "Community Apps": "Community Apps",
    "From community contributors, not optimized for CasaOS, but provides a basic App experience.": "From community contributors, not optimized for CasaOS, but provides a basic App experience.",
    "Sort by": "Sort by",


    //Storage
    "Create Storage": "Create Storage",
    "Storage Manager": "Storage Manager",
    "Storage": "Storage",
    "Drive": "Drive",
    "Single Drive Storage": "Single Drive Storage",
    "Format": "Format",
    "Remove": "Remove",
    "Available Total": "{name} | Available: {avl} (Total: {total})",
    "Health": "Health",
    "Healthy": "Healthy",
    "Damage": "Damage",
    "Temp": "Temp",
    "WARNING!": "WARNING!",
    "This selected drive will be emptied if there is data on it. Make sure again that there is no important data on the selected drive that has not been backed up. If there is data to be migrated, the related apps will be stopped during the migration process.": "This selected drive will be emptied if there is data on it. Make sure again that there is no important data on the selected drive that has not been backed up. If there is data to be migrated, the related apps will be stopped during the migration process.",
    "Creation in progress": "Creation in progress",
    "Apply": "Apply",
    "Just Mount": "Just Mount",
    "Storage Name": "Storage Name",
    "Choose Drive": "Choose Drive",
    "Enter the password to continue:": "Enter the password to continue:",
    "Used": "Used",
    "CasaOS reserves 1% of file space when creating storage in EXT4 format.": "CasaOS reserves 1% of file space when creating storage in EXT4 format.",
    "The selected drive will be emptied.": "The selected drive will be emptied.",
    "Please make sure again that there is no important data on the selected drive that needs to be backed up.": "Please make sure again that there is no important data on the selected drive that needs to be backed up.",
    "The drive you select can be used directly as storage.": "The drive you select can be used directly as storage.",
    "You can also choose to create it after formatting. If formatted, the selected drive will be emptied.": "You can also choose to create it after formatting. If formatted, the selected drive will be emptied.",
    "Format and Create": "Format and Create",

    // Feedback
    "Join Discord": "Join Discord",
    "Visit our Github": "Visit our Github",
    "Bug report": "Bug report",
    "Title": "Title",
    "Describe the bug": "Describe the bug",
    "A clear and concise description of what the bug is.": "A clear and concise description of what the bug is.",
    "System infomation": "System infomation",
}
