{
    // Commons
    "": "",
    "OK": "OK",
    "Cancel": "avbryt",
    "Submit": "Skicka",
    "Back": "Tillbaka",
    "Edit": "Redigera",
    "Update": "Uppdatera",
    "Create": "Skapa",
    "Next": "Nästa",
    "Close": "Stäng",
    "Select": "Välj",
    "Save": "Spara",
    "Add": "Lägg till",
    "Go": "Gå",
    "Import": "Importera",
    "Low": "Låg",
    "Medium": "Medium",
    "High": "Hög",
    "Language": "Språk",
    "Change": "Ändra",
    "Start": "Start",

    "This field is required": "Detta fält krävs",
    "This field must be a valid email": "Detta fält måste vara en giltig e-postadress",
    "This field confirmation does not match": "Bekräftelsen av detta fält matchar inte",
    "This field must have 2 options": "Detta fält måste ha 2 alternativ",
    "This field must have more than 5 characters": "Detta fält måste ha fler än 5 tecken",
    "You entered an invalid RFC1123 hostname": "Du angav en ogiltig RFC1123-värdnamn",
    
    // Init Page
    "Welcome to CasaOS": "Välkommen till CasaOS",
    "Let's create your initial account": "Låt oss skapa ditt inledande konto",
    "Go →": "Gå →",
    "Create Account": "Skapa konto",
    "Username": "Användarnamn",
    "Confirm Password": "Bekräfta lösenord",
    "Username or Password error!": "Användarnamn eller lösenord fel!",
    "All things done!": "Allt klart!",

    // Login
    "Login": "Logga in",
    "Password error!": "Lösenord fel!",

    // Account
    "Account": "Konto",
    "Logout": "Logga ut",
    "Name": "Namn",
    "Password": "Lösenord",
    "Change name": "Ändra namn",
    "Change Password": "Ändra lösenord",
    "Original password": "Ursprungligt lösenord",
    "New password": "Nytt lösenord",
    "Confirm the new password again": "Bekräfta det nya lösenordet igen",

    // Dashboard Settings
    "Settings": "Inställningar",
    "Dashboard Setting": "Instrumentpanelinställning",
    "Search Engine": "Sökmotor",
    "WebUI Port": "WebUI-port",
    "Currently the latest version": "För närvarande den senaste versionen",
    "A new version is available!": "En ny version är tillgänglig!",
    "Edit Web UI port": "Redigera WebUI-port",
    "Automount USB Drive": "Automount USB-enhet",
    "Wallpaper": "Bakgrundsbild",
    "Change wallpaper": "Byt bakgrundsbild",
    "Show Search Bar": "Visa sökfält",
    "Show Recommended Apps": "Visa rekommenderade appar",
    "Upgrade Now": "Uppgradera nu",
    "Enabling this function may cause boot failures when the Raspberry Pi device is booted from USB": "Aktivering av denna funktion kan orsaka startfel när Raspberry Pi-enheten startas från USB",

    // Terminal & Logs
    "Terminal & Logs": "Terminal & Loggar",
    "Terminal": "Terminal",
    "Logs": "Loggar",

    // Widgets
    "Widgets Settings": "Widgetinställningar",
    "Time": "Tid",
    "Cores": "Kärnor",
    "System Status": "Systemstatus",
    "Storage Status": "Lagringsstatus",
    "Network Status": "Nätverksstatus",
    "available of": "{avl} tillgänglig av {total}",

    // Search
    "Search...": "Sök...",

    // Sync
    "Sync your data": "Synkronisera dina data",
    "Use Syncthing to sync your files between multiple devices.": "Använd Syncthing för att synkronisera dina filer mellan flera enheter.",
    "Install": "Installera",
    "Config": "Konfig",
    "Total": "Totalt",
    "Failed to start, please try again.": "Misslyckades att starta, försök igen.",
    "Syncthing is not running, start it?": "Syncthing körs inte, starta det?",
    "Starting Syncthing...": "Startar Syncthing...",

    // Iot
    "Have an idea? Shoot it on Discord!": "Har du en idé? Skriv ett medellande på discord!",
    "Smarten up your home": "Gör ditt hem smartare",
    "We want to give you a smart home experience with privacy, high speed, and localized storage.": "Vi vill ge dig en smart hemupplevelse med integritet, hög hastighet och lokal lagring.",
    "In development": "Under utveckling",

    // Apps
    "Apps": "Appar",
    "App": "App",
    "Open": "Öppna",
    "Setting": "Inställning",
    "Uninstall": "Avinstallera",
    "Attention": "Observera",
    "Data cannot be recovered after deletion! <br>Continue on to uninstall this application?": "Data kan inte återställas efter borttagning! <br>Fortsätt att avinstallera denna applikation?",
    "Featured Apps": "Utvalda appar",
    "Custom Install": "Anpassad installation",
    "Continue in background": "Fortsätt i bakgrunden",
    "Install a new App manually": "Installera en ny app manuellt",
    "Docker Image": "Docker-bild",
    "App name": "Appnamn",
    "Icon URL": "Ikon-URL",
    "Network": "Nätverk",
    "Privileged": "Privilegierad",
    "Container Command": "Containerkommando",
    "Container Capabilities (cap-add)": "Containerförmågor (cap-add)",
    "Container Hostname": "Container-värdnamn",
    "Hostname of app container": "Värdnamn för appcontainer",
    "Ports": "Portar",
    "Volumes": "Volym",
    "Environment Variables": "Miljövariabler",
    "Devices": "Enheter",
    "Memory Limit": "Minnesgräns",
    "CPU Shares": "CPU-andelar",
    "Restart Policy": "Omplacering",
    "App Description": "Appbeskrivning",
    "No ports now, click “+” to add one.": "Inga portar nu, klicka på “+” för att lägga till en.",
    "No volumes now, click “+” to add one.": "Inga volymer nu, klicka på “+” för att lägga till en.",
    "No environment variables now, click “+” to add one.": "Inga miljövariabler nu, klicka på “+” för att lägga till en.",
    "No devices now, click “+” to add one.": "Inga enheter nu, klicka på “+” för att lägga till en.",
    "No commands now, click “+” to add one.": "Inga kommandon nu, klicka på “+” för att lägga till en.",
    "e.g.,hello-world:latest": "t.ex.,hello-world:latest",
    "Your custom App Name": "Ditt anpassade appnamn",
    "Your custom icon URL": "Din anpassade ikon-URL",
    "Installing": "Installerar",
    "Export AppFile": "Exportera AppFile",
    "AppFile": "AppFile",
    "Drop your app file here or click to upload": "Släpp din appfil här eller klicka för att ladda upp",
    "Host": "Värd",
    "Container": "Container",
    "Key": "Nyckel",
    "Value": "Värde",
    "Protocol": "Protokoll",
    "This is not a valid json file.": "Detta är inte en giltig json-fil.",
    "Your browser does not support file reading.": "Din webbläsare stöder inte filinläsning.",
    "has been selected": "har valts",
    "Please fill correct command line": "Fyll i rätt kommandorad",
    "Please import a valid App file": "Importera en giltig appfil",
    "AutoFill only helps you to complete most of the configuration.": "AutoFill hjälper dig bara att slutföra det mesta av konfigurationen.",
    "Some configuration information such as:": "Viss konfigurationsinformation som:",
    "the port and path of the Web UI": "porten och sökvägen för Web UI",
    "the mount location of the volume or file": "monteringsplatsen för volymen eller filen",
    "the port mapping of the Host": "portmappningen av värden",
    "optional configuration items": "valfria konfigurationsobjekt",
    "These include but are not limited to these cases and <b>still need to be confirmed or modified by you.</b>": "Dessa inkluder men är inte begränsade till dessa fall och <b>behöver fortfarande bekräftas eller ändras av dig.</b>",
    "Feel free to suggest improvements to this feature in Discord Server!": "Känn dig fri att föreslå förbättringar av denna funktion i Discord Server!",
    "Using localhost or 127.0.0.1 will cause the application to be inaccessible, please use the real ip to access.": " använder localhost eller 127.0.0.1 kommer att göra applikationen otillgänglig, använd den riktiga ip-adressen för att komma åt.",
    "CATEGORY": "KATEGORI",
    "DEVELOPER": "UTVECKLARE",
    "REQUIRE": "KRÄVER",
    "MEMORY": "MINNE",
    "DISK": "DISK",
    "App Store": "App Store",
    "Community Apps": "Community-appar",
    "From community contributors, not optimized for CasaOS, but provides a basic App experience.": "Från community-bidragsgivare, inte optimerad för CasaOS, men ger en grundläggande appupplevelse.",
    "Sort by": "Sortera efter",
    "Click icon to import.": "Klicka på ikonen för att importera.",
    "Drag icons to sort.": "Dra ikoner för att sortera.",
    "Import to CasaOS": "Importera till CasaOS",
    "Existing Docker Apps": "Befintliga Docker-appar",
    "Port [Please add a ports set first]": "Port [Lägg till en portuppsättning först]",
    "[Optional]": "[Valfritt]",
    "Notice: If there are multiple services, only the first set can be analyzed correctly": "Observera: Om det finns flera tjänster kan endast den första uppsättningen analyseras korrekt",
    "There was an error loading the data, please try again!": "Det uppstod ett fel vid inläsningen av data, försök igen!",

    //Storage
    "Create Storage": "Skapa lagring",
    "Storage Manager": "Lagringshanterare",
    "Storage": "Lagring",
    "Drive": "Enhet",
    "Single Drive Storage": "Enkel enhetslagring",
    "Format": "Formatera",
    "Remove": "Ta bort",
    "Available Total": "{name} | Tillgänglig: {avl} (Totalt: {total})",
    "Health": "Hälsa",
    "Healthy": "Frisk",
    "Damage": "Skada",
    "Temp": "Temp",
    "WARNING!": "VARNING!",
    "This selected drive will be emptied if there is data on it. Make sure again that there is no important data on the selected drive that has not been backed up. If there is data to be migrated, the related apps will be stopped during the migration process.": "Den valda enheten kommer att tömmas om det finns data på den. Se till att det inte finns några viktiga data på den valda enheten som inte har säkerhetskopierats. Om det finns data att migrera kommer de relaterade apparna att stoppas under migreringsprocessen.",
    "Creation in progress": "Skapande pågår",
    "Apply": "Tillämpa",
    "Just Mount": "Bara montera",
    "Storage Name": "Lagringsnamn",
    "Choose Drive": "Välj enhet",
    "Enter the password to continue:": "Ange lösenordet för att fortsätta:",
    "Used": "Använd",
    "CasaOS reserves 1% of file space when creating storage in EXT4 format.": "CasaOS reserverar 1% av filutrymmet när lagring skapas i EXT4-format.",
    "The selected drive will be emptied.": "Den valda enheten kommer att tömmas.",
    "Please make sure again that there is no important data on the selected drive that needs to be backed up.": "Se till att det inte finns några viktiga data på den valda enheten som behöver säkerhetskopieras.",
    "The drive you select can be used directly as storage.": "Den enhet du väljer kan användas direkt som lagring.",

    // Feedback
    "Join Discord": "Gå med i Discord",
    "Visit our Github": "Besök vår Github",
    "Bug report": "Felrapport",
    "Title": "Titel",
    "Describe the bug": "Beskriv felet",
    "A clear and concise description of what the bug is.": "En tydlig och kortfattad beskrivning av vad felet är.",
    "System infomation": "Systeminformation",

    // Files
    "Files": "Filer",
    "Upload or Create": "Ladda upp eller skapa",
    "Upload Files": "Ladda upp filer",
    "Upload Folder": "Ladda upp mapp",
    "New Folder": "Ny mapp",
    "New File": "Ny fil",
    "Change View": "Ändra vy",
    "Upload to": "Ladda upp till",
    "Uploading": "Laddar upp",
    "Completed": "Slutförd",
    "success": "Lyckades",
    "error": "Fel",
    "uploading": "Laddar upp",
    "paused": "Pausad",
    "waiting": "Väntar",
    "Download": "Ladda ner",
    "Copy Path": "Kopiera sökväg",
    "Rename": "Byt namn",
    "Cut": "Klipp ut",
    "Copy": "Kopiera",
    "Delete": "Radera",
    "Are you sure?": "Är du säker?",
    "Paste": "Klistra in",
    "Refresh": "Uppdatera",
    "Code Editor": "Kodredigerare",
    "Saved": "Sparad",
    "Want to save?": "Vill du spara?",
    "Your changes will be lost if you don’t save them.": "Dina ändringar kommer att gå förlorade om du inte sparar dem.",
    "Don’t Save": "Spara inte",
    "Drop your files here to upload": "Släpp dina filer här för att ladda upp",
    "or": "eller",
    "Date Modified": "Ändringsdatum",
    "Size": "Storlek",
    "Play in IINA": "Spela i IINA",
    "Play in PotPlayer": "Spela i PotPlayer",
    "Play in VLC": "Spela i VLC",
    "Download in preparation...": "Ladda ner förberedelse...",
    "Copied to clipboard": "Kopierad till urklipp",
    "Previous": "Föregående",
    "Zoom in": "Zooma in",
    "Rotate": "Rotera",
    "Reset": "Återställ",
    "Zoom out": "Zooma ut",
    "INext": "Nästa",
    "Move": "Flytta",
    "Current Tasks": "Aktuella uppgifter",
    "Deleting files": "Raderar filer",
    "Are you sure you want to <b>delete</b> these files? This action cannot be undone.": "Är du säker på att du vill <b>radera</b> dessa filer? Denna åtgärd kan inte ångras.",
    "select-items": "Välj {num} objekt",
    "total-items": "Totalt {num} objekt",
    "cancel-all": "Avbryt alla",
    "Paste - Overwrite": "Klistra in - Skriv över",
    "Paste - Skip": "Klistra in - Hoppa över",
    "Set as wallpaper": "Ange som bakgrundsbild",
    "Set wallpaper successfully.": "Ange bakgrundsbild framgångsrikt.",
    "Save failed, please try again!": "Sparande misslyckades, försök igen!",
    "Upload failed, please try again!": "Uppladdning misslyckades, försök igen!",
}
